//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrayPal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrayPal.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אודות.
        /// </summary>
        public static string AboutCommandTitle {
            get {
                return ResourceManager.GetString("AboutCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פותח על-ידי חיים בורלא.
        ///נעשה שימוש בספריית הזמנים Zmanim..
        /// </summary>
        public static string AboutText1 {
            get {
                return ResourceManager.GetString("AboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrayPal.
        /// </summary>
        public static string AboutViewTitle {
            get {
                return ResourceManager.GetString("AboutViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לאחר ההפטרה.
        /// </summary>
        public static string AfterHaftarahTitle {
            get {
                return ResourceManager.GetString("AfterHaftarahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אחרי חזרת הש&quot;ץ.
        /// </summary>
        public static string AfterHazarahTitle {
            get {
                return ResourceManager.GetString("AfterHazarahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אחרי אמירת תהילים.
        /// </summary>
        public static string AfterPsalmTitle {
            get {
                return ResourceManager.GetString("AfterPsalmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עלינו לשבח.
        /// </summary>
        public static string AleinuLeshabeachTitle {
            get {
                return ResourceManager.GetString("AleinuLeshabeachTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחנוכה.
        /// </summary>
        public static string AlHanissimHannukahTitle {
            get {
                return ResourceManager.GetString("AlHanissimHannukahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בפורים.
        /// </summary>
        public static string AlHanissimPurimTitle {
            get {
                return ResourceManager.GetString("AlHanissimPurimTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וְ.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrayPal.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מאתר מיקום נוכחי....
        /// </summary>
        public static string AqcuiringCurrentLocation {
            get {
                return ResourceManager.GetString("AqcuiringCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לאתר מיקום נוכחי.
        /// </summary>
        public static string AqcuiringCurrentLocationFailed {
            get {
                return ResourceManager.GetString("AqcuiringCurrentLocationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכת אשר יצר.
        /// </summary>
        public static string AsherYatzarTitle {
            get {
                return ResourceManager.GetString("AsherYatzarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אשרי.
        /// </summary>
        public static string AshreyTitle {
            get {
                return ResourceManager.GetString("AshreyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עטיפת טלית.
        /// </summary>
        public static string AtifatTalitTitle {
            get {
                return ResourceManager.GetString("AtifatTalitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אבינו מלכנו.
        /// </summary>
        public static string AvinuMalkenuTitle {
            get {
                return ResourceManager.GetString("AvinuMalkenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בעשי&quot;ת.
        /// </summary>
        public static string AYTTitlt {
            get {
                return ResourceManager.GetString("AYTTitlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכי נפשי.
        /// </summary>
        public static string BarchiNafshiTitle {
            get {
                return ResourceManager.GetString("BarchiNafshiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קריאת שמע על המיטה.
        /// </summary>
        public static string BedtimeShmaTitle {
            get {
                return ResourceManager.GetString("BedtimeShmaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לפני אמירת תהילים.
        /// </summary>
        public static string BeforePsalmTitle {
            get {
                return ResourceManager.GetString("BeforePsalmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכת כהנים בתענית ציבור (בחזרת הש&quot;ץ).
        /// </summary>
        public static string BirkatCohanimInTeanitTitle {
            get {
                return ResourceManager.GetString("BirkatCohanimInTeanitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכת כהנים (בחזרת הש&quot;ץ).
        /// </summary>
        public static string BirkatCohanimTitle {
            get {
                return ResourceManager.GetString("BirkatCohanimTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכת הזן.
        /// </summary>
        public static string BirkatHamazon1Title {
            get {
                return ResourceManager.GetString("BirkatHamazon1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עד 72 דקות אחרי האכילה.
        /// </summary>
        public static string BirkatHaMazonEndTimeInstruction {
            get {
                return ResourceManager.GetString("BirkatHaMazonEndTimeInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכת המזון.
        /// </summary>
        public static string BirkatHamazonTitle {
            get {
                return ResourceManager.GetString("BirkatHamazonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכת האורח.
        /// </summary>
        public static string BirkatHaoreach {
            get {
                return ResourceManager.GetString("BirkatHaoreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכת נשמה.
        /// </summary>
        public static string BirkatNeshamaTitle {
            get {
                return ResourceManager.GetString("BirkatNeshamaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכות השחר.
        /// </summary>
        public static string BirkotHashacharTitle {
            get {
                return ResourceManager.GetString("BirkotHashacharTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכות התורה.
        /// </summary>
        public static string BirkotHatorahTitle {
            get {
                return ResourceManager.GetString("BirkotHatorahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכנה לברכה.
        /// </summary>
        public static string BlessingPreparation {
            get {
                return ResourceManager.GetString("BlessingPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ספרות.
        /// </summary>
        public static string BooksTitle {
            get {
                return ResourceManager.GetString("BooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכות קריאת שמע.
        /// </summary>
        public static string BrachotKriatShmaTitle {
            get {
                return ResourceManager.GetString("BrachotKriatShmaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברייתא דרבי ישמעאל.
        /// </summary>
        public static string BrayitaDerabiYishmaelTitle {
            get {
                return ResourceManager.GetString("BrayitaDerabiYishmaelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לוח שנה.
        /// </summary>
        public static string CalendarTitle {
            get {
                return ResourceManager.GetString("CalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כייל מצפן.
        /// </summary>
        public static string CalibrateCompassCommandTitle {
            get {
                return ResourceManager.GetString("CalibrateCompassCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כדי לכייל את המצפן, הזז את הטלפון בצורת הספרה 8 מספר פעמים..
        /// </summary>
        public static string CalibrateCompassInstruction {
            get {
                return ResourceManager.GetString("CalibrateCompassInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כיול מצפן.
        /// </summary>
        public static string CalibrateCompassPageTitle {
            get {
                return ResourceManager.GetString("CalibrateCompassPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מכוייל.
        /// </summary>
        public static string CalibrateCompassStatusCalibrated {
            get {
                return ResourceManager.GetString("CalibrateCompassStatusCalibrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא מכוייל.
        /// </summary>
        public static string CalibrateCompassStatusNotCalibrated {
            get {
                return ResourceManager.GetString("CalibrateCompassStatusNotCalibrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רמת דיוק:.
        /// </summary>
        public static string CalibrateCompassStatusTitle {
            get {
                return ResourceManager.GetString("CalibrateCompassStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עבור מראת תפילין בשחרית.
        /// </summary>
        public static string CameraPermissionReason {
            get {
                return ResourceManager.GetString("CameraPermissionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מצלמה.
        /// </summary>
        public static string CameraPermissionTitle {
            get {
                return ResourceManager.GetString("CameraPermissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;לא ניתן לטעון תוכן&gt;.
        /// </summary>
        public static string CannotLoadContentError {
            get {
                return ResourceManager.GetString("CannotLoadContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניתן ללחוץ על הכותרות הגדולות כדי לקפוץ למיקום מסויים בטקסט.
        /// </summary>
        public static string ClickDocHeaderInstruction {
            get {
                return ResourceManager.GetString("ClickDocHeaderInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לחץ כאן.
        /// </summary>
        public static string ClickHereLabel {
            get {
                return ResourceManager.GetString("ClickHereLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כהן.
        /// </summary>
        public static string CohenTitle {
            get {
                return ResourceManager.GetString("CohenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משוערת.
        /// </summary>
        public static string CompassAccuracyApproximate {
            get {
                return ResourceManager.GetString("CompassAccuracyApproximate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גבוהה.
        /// </summary>
        public static string CompassAccuracyHigh {
            get {
                return ResourceManager.GetString("CompassAccuracyHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ידועה.
        /// </summary>
        public static string CompassAccuracyUnknown {
            get {
                return ResourceManager.GetString("CompassAccuracyUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא אמינה.
        /// </summary>
        public static string CompassAccuracyUnreliable {
            get {
                return ResourceManager.GetString("CompassAccuracyUnreliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש לכייל את המצפן. לחץ למטה על &quot;כייל מצפן&quot;..
        /// </summary>
        public static string CompassCalibrationNeeded {
            get {
                return ResourceManager.GetString("CompassCalibrationNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לקרוא נתונים מהמצפן..
        /// </summary>
        public static string CompassCannotBeReadError {
            get {
                return ResourceManager.GetString("CompassCannotBeReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to למכשיר זה אין תמיכה במצפן.
        /// </summary>
        public static string CompassNotSupported {
            get {
                return ResourceManager.GetString("CompassNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צור קשר.
        /// </summary>
        public static string ContactUsCommandTitle {
            get {
                return ResourceManager.GetString("ContactUsCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיר של יום.
        /// </summary>
        public static string DayVerseTitle {
            get {
                return ResourceManager.GetString("DayVerseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיר של יום - {0}.
        /// </summary>
        public static string DayVerseTitle_F0 {
            get {
                return ResourceManager.GetString("DayVerseTitle_F0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to haim_burla@hotmail.com.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש לוודא ששירותי המיקום פועלים במסך.
        /// </summary>
        public static string EnablingSysLocationInstruction1 {
            get {
                return ResourceManager.GetString("EnablingSysLocationInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות המיקום.
        /// </summary>
        public static string EnablingSysLocationInstruction2 {
            get {
                return ResourceManager.GetString("EnablingSysLocationInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to של מערכת ההפעלה..
        /// </summary>
        public static string EnablingSysLocationInstruction3 {
            get {
                return ResourceManager.GetString("EnablingSysLocationInstruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוף זמן תפילה.
        /// </summary>
        public static string EndTimeOfPrayer {
            get {
                return ResourceManager.GetString("EndTimeOfPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גודל טקסט בתפילות:.
        /// </summary>
        public static string FontSizeSettingLabel {
            get {
                return ResourceManager.GetString("FontSizeSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גדול.
        /// </summary>
        public static string FontSizeSettingLabelLarge {
            get {
                return ResourceManager.GetString("FontSizeSettingLabelLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רגיל.
        /// </summary>
        public static string FontSizeSettingLabelRegular {
            get {
                return ResourceManager.GetString("FontSizeSettingLabelRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to למוצאי שבת.
        /// </summary>
        public static string ForMotzashTitle {
            get {
                return ResourceManager.GetString("ForMotzashTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רביעי.
        /// </summary>
        public static string ForthTorahReaderTitle {
            get {
                return ResourceManager.GetString("ForthTorahReaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצג.
        /// </summary>
        public static string GoToButtonTitle {
            get {
                return ResourceManager.GetString("GoToButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות מסך נעילה.
        /// </summary>
        public static string GoToLockScreenSettingsCommandTitle {
            get {
                return ResourceManager.GetString("GoToLockScreenSettingsCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניתן להזין אותיות או ספרות.
        /// </summary>
        public static string GoToPsalmVerseInstruction {
            get {
                return ResourceManager.GetString("GoToPsalmVerseInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרק:.
        /// </summary>
        public static string GoToPsalmVerseTitle {
            get {
                return ResourceManager.GetString("GoToPsalmVerseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to היום.
        /// </summary>
        public static string GoToTodayCommandTitle {
            get {
                return ResourceManager.GetString("GoToTodayCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גר&quot;א (למקלים).
        /// </summary>
        public static string Gra {
            get {
                return ResourceManager.GetString("Gra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הדלקת נרות חנוכה.
        /// </summary>
        public static string HadlakatNerotHannukahTitle {
            get {
                return ResourceManager.GetString("HadlakatNerotHannukahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכות ההפטרה.
        /// </summary>
        public static string HaftarahBlessingTitle {
            get {
                return ResourceManager.GetString("HaftarahBlessingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפטרה.
        /// </summary>
        public static string HaftarahTitle {
            get {
                return ResourceManager.GetString("HaftarahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגבהה.
        /// </summary>
        public static string HagbahaTitle {
            get {
                return ResourceManager.GetString("HagbahaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגבהה וגלילה.
        /// </summary>
        public static string HagbahaVeglilahTitle {
            get {
                return ResourceManager.GetString("HagbahaVeglilahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הלל.
        /// </summary>
        public static string HallelTitle {
            get {
                return ResourceManager.GetString("HallelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הנחת תפילין.
        /// </summary>
        public static string HanachatTfillinTitle {
            get {
                return ResourceManager.GetString("HanachatTfillinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הנרות הללו.
        /// </summary>
        public static string HanerotHalaluTitle {
            get {
                return ResourceManager.GetString("HanerotHalaluTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר ראשון.
        /// </summary>
        public static string HannukaCandle1 {
            get {
                return ResourceManager.GetString("HannukaCandle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר שני.
        /// </summary>
        public static string HannukaCandle2 {
            get {
                return ResourceManager.GetString("HannukaCandle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר שלישי.
        /// </summary>
        public static string HannukaCandle3 {
            get {
                return ResourceManager.GetString("HannukaCandle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר רביעי.
        /// </summary>
        public static string HannukaCandle4 {
            get {
                return ResourceManager.GetString("HannukaCandle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר חמישי.
        /// </summary>
        public static string HannukaCandle5 {
            get {
                return ResourceManager.GetString("HannukaCandle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר שישי.
        /// </summary>
        public static string HannukaCandle6 {
            get {
                return ResourceManager.GetString("HannukaCandle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר שביעי.
        /// </summary>
        public static string HannukaCandle7 {
            get {
                return ResourceManager.GetString("HannukaCandle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר שמיני.
        /// </summary>
        public static string HannukaCandle8 {
            get {
                return ResourceManager.GetString("HannukaCandle8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכות על {0}.
        /// </summary>
        public static string HannukahCandleBlessingTitle {
            get {
                return ResourceManager.GetString("HannukahCandleBlessingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מניחים את הנרות מימין לשמאל ומדליקים משמאל לימין..
        /// </summary>
        public static string HannukahCandlesOrderInstruction {
            get {
                return ResourceManager.GetString("HannukahCandlesOrderInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סדר הדלקת הנרות.
        /// </summary>
        public static string HannukahCandlesOrderTitle {
            get {
                return ResourceManager.GetString("HannukahCandlesOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חצי קדיש.
        /// </summary>
        public static string HaziKadishTitle {
            get {
                return ResourceManager.GetString("HaziKadishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מראה לתפילין של ראש.
        /// </summary>
        public static string HeadTfillinMirrorTitle {
            get {
                return ResourceManager.GetString("HeadTfillinMirrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איגרת הרמב&quot;ן.
        /// </summary>
        public static string IgerretHarambanTitle {
            get {
                return ResourceManager.GetString("IgerretHarambanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחזרת הש&quot;ץ.
        /// </summary>
        public static string InHazarahTitle {
            get {
                return ResourceManager.GetString("InHazarahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בבית האבל.
        /// </summary>
        public static string InMourningHouseTitle {
            get {
                return ResourceManager.GetString("InMourningHouseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בתפילה עם עדות המזרח.
        /// </summary>
        public static string InPrayerWithEdotHaMizrach {
            get {
                return ResourceManager.GetString("InPrayerWithEdotHaMizrach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בתפילת הלחש אומר.
        /// </summary>
        public static string InTfilatYachidTitle {
            get {
                return ResourceManager.GetString("InTfilatYachidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ישראל.
        /// </summary>
        public static string IsraelTitle {
            get {
                return ResourceManager.GetString("IsraelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קדיש דרבנן.
        /// </summary>
        public static string KadishDerabananTitle {
            get {
                return ResourceManager.GetString("KadishDerabananTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בימות השנה.
        /// </summary>
        public static string KadishLeelaRegularTitle {
            get {
                return ResourceManager.GetString("KadishLeelaRegularTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קדיש שלם.
        /// </summary>
        public static string KadishShalemTitle {
            get {
                return ResourceManager.GetString("KadishShalemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קדיש יתום.
        /// </summary>
        public static string KadishYatomTitle {
            get {
                return ResourceManager.GetString("KadishYatomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בעשרת ימי תשובה.
        /// </summary>
        public static string KadisLeelaAYT {
            get {
                return ResourceManager.GetString("KadisLeelaAYT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קדושה דסידרא.
        /// </summary>
        public static string KdushaDesidraTitle {
            get {
                return ResourceManager.GetString("KdushaDesidraTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קדושה (בחזרת הש&quot;ץ).
        /// </summary>
        public static string KdushaTitle {
            get {
                return ResourceManager.GetString("KdushaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קריאת שמע וברכותיה.
        /// </summary>
        public static string KriatShmaAndBlessingTitle {
            get {
                return ResourceManager.GetString("KriatShmaAndBlessingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קריאת שמע.
        /// </summary>
        public static string KriatShmaTitle {
            get {
                return ResourceManager.GetString("KriatShmaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קטורת הסמים.
        /// </summary>
        public static string KtoretHasamimTitle {
            get {
                return ResourceManager.GetString("KtoretHasamimTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ספר הכוזרי.
        /// </summary>
        public static string KuzariTitle {
            get {
                return ResourceManager.GetString("KuzariTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אורך.
        /// </summary>
        public static string LengthTitle {
            get {
                return ResourceManager.GetString("LengthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לשם ייחוד.
        /// </summary>
        public static string LeshemYichudTitle {
            get {
                return ResourceManager.GetString("LeshemYichudTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לוי.
        /// </summary>
        public static string LeviTitle {
            get {
                return ResourceManager.GetString("LeviTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טוען ספר....
        /// </summary>
        public static string LoadingBookProgressText {
            get {
                return ResourceManager.GetString("LoadingBookProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to למכשיר זה אין תמיכה בשירותי מיקום.
        /// </summary>
        public static string LocationNotSupported {
            get {
                return ResourceManager.GetString("LocationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך שהאפליקציה תשתמש במיקום שלך לחישוב הזמנים?.
        /// </summary>
        public static string LocationPermissionRequest {
            get {
                return ResourceManager.GetString("LocationPermissionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מיקום.
        /// </summary>
        public static string LocationPermissionRequestTitle {
            get {
                return ResourceManager.GetString("LocationPermissionRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מיקום.
        /// </summary>
        public static string LocationPermissionTitle {
            get {
                return ResourceManager.GetString("LocationPermissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש להפעיל שימוש במיקום.
        /// </summary>
        public static string LocationServicesAreNeeded {
            get {
                return ResourceManager.GetString("LocationServicesAreNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מרכז היהדות יכול להציג במסך הנעילה שלך תאריך עברי ומועדים..
        /// </summary>
        public static string LockScreenSupportInfo {
            get {
                return ResourceManager.GetString("LockScreenSupportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מעוז צור.
        /// </summary>
        public static string MaozTzurTitle {
            get {
                return ResourceManager.GetString("MaozTzurTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to על שבעת המינים.
        /// </summary>
        public static string MeeinShalosh7KindsTitle {
            get {
                return ResourceManager.GetString("MeeinShalosh7KindsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to על חמשת מיני דגן.
        /// </summary>
        public static string MeeinShaloshDaganTitle {
            get {
                return ResourceManager.GetString("MeeinShaloshDaganTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מעין שלוש.
        /// </summary>
        public static string MeeinShaloshTitle {
            get {
                return ResourceManager.GetString("MeeinShaloshTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to על יין.
        /// </summary>
        public static string MeeinShaloshWineTitle {
            get {
                return ResourceManager.GetString("MeeinShaloshWineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביטול.
        /// </summary>
        public static string MessageBoxCancel {
            get {
                return ResourceManager.GetString("MessageBoxCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא.
        /// </summary>
        public static string MessageBoxNo {
            get {
                return ResourceManager.GetString("MessageBoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אישור.
        /// </summary>
        public static string MessageBoxOK {
            get {
                return ResourceManager.GetString("MessageBoxOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כן.
        /// </summary>
        public static string MessageBoxYes {
            get {
                return ResourceManager.GetString("MessageBoxYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מגן אברהם (למחמירים).
        /// </summary>
        public static string Mga {
            get {
                return ResourceManager.GetString("Mga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המזמור לפני ארון ה&apos;.
        /// </summary>
        public static string MizmorLifneyHaAronTitle {
            get {
                return ResourceManager.GetString("MizmorLifneyHaAronTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מזמור תהילים.
        /// </summary>
        public static string MizmorTehillim {
            get {
                return ResourceManager.GetString("MizmorTehillim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודים דרבנן.
        /// </summary>
        public static string ModimDeRabananTitle {
            get {
                return ResourceManager.GetString("ModimDeRabananTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לאחר נטילת ידיים אומר.
        /// </summary>
        public static string MorningNetilatYadayimInstruction {
            get {
                return ResourceManager.GetString("MorningNetilatYadayimInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפילת מוסף.
        /// </summary>
        public static string MussafTitle {
            get {
                return ResourceManager.GetString("MussafTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש לאפשר את השימוש במיקום במסך ההגדרות של האפליקציה..
        /// </summary>
        public static string NeedToEnableAppLocationMessage {
            get {
                return ResourceManager.GetString("NeedToEnableAppLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש לאפשר את שירותי המיקום במסך ההגדרות של מערכת ההפעלה..
        /// </summary>
        public static string NeedToEnableSysLocationMessage {
            get {
                return ResourceManager.GetString("NeedToEnableSysLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נפילת אפיים.
        /// </summary>
        public static string NefilatAppayimTitle {
            get {
                return ResourceManager.GetString("NefilatAppayimTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אשכנז.
        /// </summary>
        public static string NusachAshkenazTitle {
            get {
                return ResourceManager.GetString("NusachAshkenazTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בלדי.
        /// </summary>
        public static string NusachBaladiTitle {
            get {
                return ResourceManager.GetString("NusachBaladiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדות המזרח.
        /// </summary>
        public static string NusachEdotMizrachTitle {
            get {
                return ResourceManager.GetString("NusachEdotMizrachTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נוסח:.
        /// </summary>
        public static string NusachSettingLabel {
            get {
                return ResourceManager.GetString("NusachSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ספרד.
        /// </summary>
        public static string NusachSfardTitle {
            get {
                return ResourceManager.GetString("NusachSfardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to של ישראל.
        /// </summary>
        public static string OfIsraelTitle {
            get {
                return ResourceManager.GetString("OfIsraelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האפליקציה לא הצליחה לאתר את המיקום. ספירת העומר תתעדכן רק ב-12 בלילה..
        /// </summary>
        public static string OmerCountNoLocationWarning {
            get {
                return ResourceManager.GetString("OmerCountNoLocationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ספירת העומר.
        /// </summary>
        public static string OmerCountTitle {
            get {
                return ResourceManager.GetString("OmerCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האפליקציה לא מורשית להשתמש במיקום. ספירת העומר תתעדכן רק ב-12 בלילה..
        /// </summary>
        public static string OmerCountUnusedLocationWarning {
            get {
                return ResourceManager.GetString("OmerCountUnusedLocationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרשת ברכת כהנים.
        /// </summary>
        public static string ParashatBirkatCohanimTitle {
            get {
                return ResourceManager.GetString("ParashatBirkatCohanimTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרשת העקדה.
        /// </summary>
        public static string ParashatHaakedahTitle {
            get {
                return ResourceManager.GetString("ParashatHaakedahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פתח אליהו.
        /// </summary>
        public static string PatachEliyahuTitle {
            get {
                return ResourceManager.GetString("PatachEliyahuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מעדכן האריח החי של מרכז היהדות.
        /// </summary>
        public static string PeriodicTaskDescription {
            get {
                return ResourceManager.GetString("PeriodicTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האפליקציה זקוקה להרשאות כדי לפעול באופן תקין.
        ///להלן פירוט של מה נעשה עם ההרשאות. לא יעשה דבר מעבר..
        /// </summary>
        public static string PermissionsTableInstruction {
            get {
                return ResourceManager.GetString("PermissionsTableInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיום התפילה.
        /// </summary>
        public static string PrayerEndingTitle {
            get {
                return ResourceManager.GetString("PrayerEndingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפילות וברכות.
        /// </summary>
        public static string PrayersAndGracesTitle {
            get {
                return ResourceManager.GetString("PrayersAndGracesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כיוון תפילה.
        /// </summary>
        public static string PrayingDirectionTitle {
            get {
                return ResourceManager.GetString("PrayingDirectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיר למעלות.
        /// </summary>
        public static string Psalm121Title {
            get {
                return ResourceManager.GetString("Psalm121Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהילים ליום {0} בחודש.
        /// </summary>
        public static string PsalmForMonthDayTitleFormat {
            get {
                return ResourceManager.GetString("PsalmForMonthDayTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} בחודש.
        /// </summary>
        public static string PsalmForMonthDayTitleShortFormat {
            get {
                return ResourceManager.GetString("PsalmForMonthDayTitleShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהילים ל{0}.
        /// </summary>
        public static string PsalmForTitleFormat {
            get {
                return ResourceManager.GetString("PsalmForTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהילים {0}.
        /// </summary>
        public static string PsalmTitle {
            get {
                return ResourceManager.GetString("PsalmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לפי שבוע: {0} לפי חודש: {1}.
        /// </summary>
        public static string PsalmVerseInfoFormat {
            get {
                return ResourceManager.GetString("PsalmVerseInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרקים {0}-{1}.
        /// </summary>
        public static string PsalmVerseRangeFormat {
            get {
                return ResourceManager.GetString("PsalmVerseRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרק {0}.
        /// </summary>
        public static string PsalmVerseTitleFormat {
            get {
                return ResourceManager.GetString("PsalmVerseTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פסוקי דזמרה.
        /// </summary>
        public static string PsukeyDezimraTitle {
            get {
                return ResourceManager.GetString("PsukeyDezimraTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דרג.
        /// </summary>
        public static string RateUsCommandTitle {
            get {
                return ResourceManager.GetString("RateUsCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לדיווח על טעויות, באגים, הצעות או סתם מילה טובה, .
        /// </summary>
        public static string ReportingLabel {
            get {
                return ResourceManager.GetString("ReportingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעות בלוח השנה.
        /// </summary>
        public static string ReportIssueCalendar {
            get {
                return ResourceManager.GetString("ReportIssueCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דווח.
        /// </summary>
        public static string ReportIssueCommandTitle {
            get {
                return ResourceManager.GetString("ReportIssueCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך לדווח על טעות או לבקש בקשה?.
        /// </summary>
        public static string ReportMistakeQuestion {
            get {
                return ResourceManager.GetString("ReportMistakeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הענק הרשאות.
        /// </summary>
        public static string RequestAllPermissionsCommandTitle {
            get {
                return ResourceManager.GetString("RequestAllPermissionsCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightToLeft.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to he-IL.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפילת שמונה עשרה.
        /// </summary>
        public static string SE_Title {
            get {
                return ResourceManager.GetString("SE_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סדר השכמה.
        /// </summary>
        public static string SederHashkamaTitle {
            get {
                return ResourceManager.GetString("SederHashkamaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכת הזמן.
        /// </summary>
        public static string ShehecheyanuTitle {
            get {
                return ResourceManager.GetString("ShehecheyanuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שירת הים.
        /// </summary>
        public static string ShiratHayamTitle {
            get {
                return ResourceManager.GetString("ShiratHayamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצג תפילות לעצירת גשמים.
        /// </summary>
        public static string ShowVeanenu {
            get {
                return ResourceManager.GetString("ShowVeanenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עכשיו.
        /// </summary>
        public static string SummaryNowTitle {
            get {
                return ResourceManager.GetString("SummaryNowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השבוע.
        /// </summary>
        public static string SummaryThisWeekTitle {
            get {
                return ResourceManager.GetString("SummaryThisWeekTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to היום.
        /// </summary>
        public static string SummaryTodayTitle {
            get {
                return ResourceManager.GetString("SummaryTodayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תקציר.
        /// </summary>
        public static string SummaryViewTitle {
            get {
                return ResourceManager.GetString("SummaryViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זריחה.
        /// </summary>
        public static string Sunrise {
            get {
                return ResourceManager.GetString("Sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שקיעה.
        /// </summary>
        public static string Sunset {
            get {
                return ResourceManager.GetString("Sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוכן.
        /// </summary>
        public static string TableOfContentsTitle {
            get {
                return ResourceManager.GetString("TableOfContentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סדר תחנון.
        /// </summary>
        public static string TachanunTitle {
            get {
                return ResourceManager.GetString("TachanunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלית ותפילין.
        /// </summary>
        public static string TalitAndTfillinTitle {
            get {
                return ResourceManager.GetString("TalitAndTfillinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דִּרְשׁ֥וּ יְהוָ֖ה בְּהִמָּצְא֑וֹ קְרָאֻ֖הוּ בִּֽהְיוֹת֥וֹ קָרֽוֹב ׃ יַעֲזֹ֤ב רָשָׁע֙ דַּרְכּ֔וֹ וְאִ֥ישׁ אָ֖וֶן מַחְשְׁבֹתָ֑יו וְיָשֹׁ֤ב אֶל־יְהוָה֙ וִֽירַחֲמֵ֔הוּ וְאֶל־אֱלֹהֵ֖ינוּ כִּֽי־יַרְבֶּ֥ה לִסְלֽוֹחַ ׃  כִּ֣י לֹ֤א מַחְשְׁבוֹתַי֙ מַחְשְׁב֣וֹתֵיכֶ֔ם וְלֹ֥א דַרְכֵיכֶ֖ם דְּרָכָ֑י נְאֻ֖ם יְהוָֽה ׃  כִּֽי־גָבְה֥וּ שָׁמַ֖יִם מֵאָ֑רֶץ כֵּ֣ן גָּבְה֤וּ דְרָכַי֙ מִדַּרְכֵיכֶ֔ם וּמַחְשְׁבֹתַ֖י מִמַּחְשְׁבֹתֵיכֶֽם ׃  כִּ֡י כַּאֲשֶׁ֣ר יֵרֵד֩ הַגֶּ֨שֶׁם וְהַשֶּׁ֜לֶג מִן־הַשָּׁמַ֗יִם וְשָׁ֨מָּה֙ לֹ֣א יָשׁ֔וּב כִּ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TeanitHaftarah {
            get {
                return ResourceManager.GetString("TeanitHaftarah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כהן: וַיְחַ֣ל מֹשֶׁ֔ה אֶת־פְּנֵ֖י יְהוָ֣ה אֱלֹהָ֑יו וַיֹּ֗אמֶר לָמָ֤ה יְהוָה֙ יֶחֱרֶ֤ה אַפְּךָ֙ בְּעַמֶּ֔ךָ אֲשֶׁ֤ר הוֹצֵ֙אתָ֙ מֵאֶ֣רֶץ מִצְרַ֔יִם בְּכֹ֥חַ גָּד֖וֹל וּבְיָ֥ד חֲזָקָֽה׃ לָמָּה֩ יֹאמְר֨וּ מִצְרַ֜יִם לֵאמֹ֗ר בְּרָעָ֤ה הֽוֹצִיאָם֙ לַהֲרֹ֤ג אֹתָם֙ בֶּֽהָרִ֔ים וּ֨לְכַלֹּתָ֔ם מֵעַ֖ל פְּנֵ֣י הָֽאֲדָמָ֑ה שׁ֚וּב מֵחֲר֣וֹן אַפֶּ֔ךָ וְהִנָּחֵ֥ם עַל־הָרָעָ֖ה לְעַמֶּֽךָ׃ זְכֹ֡ר לְאַבְרָהָם֩ לְיִצְחָ֨ק וּלְיִשְׂרָאֵ֜ל עֲבָדֶ֗יךָ אֲשֶׁ֨ר נִשְׁבַּ֣עְתָּ לָהֶם֮ בָּךְ֒ וַתְּדַבֵּ֣ר אֲלֵהֶ֔ם אַרְבֶּה֙ אֶֽת־זַרְ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TeanitReading {
            get {
                return ResourceManager.GetString("TeanitReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְחַ֣ל מֹשֶׁ֔ה אֶת־פְּנֵ֖י יְהוָ֣ה אֱלֹהָ֑יו וַיֹּ֗אמֶר לָמָ֤ה יְהוָה֙ יֶחֱרֶ֤ה אַפְּךָ֙ בְּעַמֶּ֔ךָ אֲשֶׁ֤ר הוֹצֵ֨אתָ֙ מֵאֶ֣רֶץ מִצְרַ֔יִם בְּכֹ֥חַ גָּד֖וֹל וּבְיָ֥ד חֲזָקָֽה ׃  לָמָּה֩ יֹאמְר֨וּ מִצְרַ֜יִם לֵאמֹ֗ר בְּרָעָ֤ה הֽוֹצִיאָם֙ לַהֲרֹ֤ג אֹתָם֙ בֶּֽהָרִ֔ים וּ֨לְכַלֹּתָ֔ם מֵעַ֖ל פְּנֵ֣י הָֽאֲדָמָ֑ה שׁוּב מֵחֲר֣וֹן אַפֶּ֔ךָ וְהִנָּחֵ֥ם עַל־הָרָעָ֖ה לְעַמֶּֽךָ ׃  זְכֹ֡ר לְאַבְרָהָם֩ לְיִצְחָ֨ק וּלְיִשְׂרָאֵ֜ל עֲבָדֶ֗יךָ אֲשֶׁ֨ר נִשְׁבַּ֣עְתָּ לָהֶם֮ בָּךְ֒ וַתְּדַבֵּ֣ר אֲלֵהֶ֔ם אַרְבֶּה֙ אֶֽת־זַרְעֲ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TeanitReadingCohen {
            get {
                return ResourceManager.GetString("TeanitReadingCohen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיִּפְסֹ֡ל שְׁנֵֽי־לֻחֹ֨ת אֲבָנִ֜ים כָּרִאשֹׁנִ֗ים וַיַּשְׁכֵּ֨ם מֹשֶׁ֤ה בַבֹּ֨קֶר֙ וַיַּ֨עַל֙ אֶל־הַ֣ר סִינַ֔י כַּאֲשֶׁ֛ר צִוָּ֥ה יְהוָ֖ה אֹת֑וֹ וַיִּקַּ֣ח בְּיָד֔וֹ שְׁנֵ֖י לֻחֹ֥ת אֲבָנִֽים ׃  וַיֵּ֤רֶד יְהוָה֙ בֶּֽעָנָ֔ן וַיִּתְיַצֵּ֥ב עִמּ֖וֹ שָׁ֑ם וַיִּקְרָ֥א בְשֵׁ֖ם יְהוָֽה ׃  וַיַּעֲבֹ֨ר יְהוָ֥ה׀ עַל־פָּנָיו֮ וַיִּקְרָא֒ יְהוָ֣ה׀ יְהוָ֔ה אֵ֥ל רַח֖וּם וְחַנּ֑וּן אֶ֥רֶךְ אַפַּ֖יִם וְרַב־חֶ֥סֶד וֶאֱמֶֽת ׃  נֹצֵ֥ר חֶ֨סֶד֙ לָאֲלָפִ֔ים נֹשֵׂ֥א עָוֹ֛ן וָפֶ֖שַׁע וְחַטָּאָ֑ה וְנַקֵּה֙ לֹ֣א יְנַקֶּ֔ה פֹּקֵ֣ד׀ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TeanitReadingIsrael {
            get {
                return ResourceManager.GetString("TeanitReadingIsrael", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיֹּ֤אמֶר יְהוָה֙ אֶל־מֹשֶׁ֔ה פְּסָל־לְךָ֛ שְׁנֵֽי־לֻחֹ֥ת אֲבָנִ֖ים כָּרִאשֹׁנִ֑ים וְכָתַבְתִּי֙ עַל־הַלֻּחֹ֔ת אֶת־הַדְּבָרִ֔ים אֲשֶׁ֥ר הָי֛וּ עַל־הַלֻּחֹ֥ת הָרִאשֹׁנִ֖ים אֲשֶׁ֥ר שִׁבַּֽרְתָּ ׃  וֶהְיֵ֥ה נָכ֖וֹן לַבֹּ֑קֶר וְעָלִ֤יתָ בַבֹּ֨קֶר֙ אֶל־הַ֣ר סִינַ֔י וְנִצַּבְתָּ֥ לִ֛י שָׁ֖ם עַל־רֹ֥אשׁ הָהָֽר ׃  וְאִישׁ֙ לֹֽא־יַעֲלֶ֣ה עִמָּ֔ךְ וְגַם־אִ֥ישׁ אַל־יֵרָ֖א בְּכָל־הָהָ֑ר גַּם־הַצֹּ֤אן וְהַבָּקָר֙ אַל־יִרְע֔וּ אֶל־מ֖וּל הָהָ֥ר הַהֽוּא ׃.
        /// </summary>
        public static string TeanitReadingLevi {
            get {
                return ResourceManager.GetString("TeanitReadingLevi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהילים.
        /// </summary>
        public static string TehillimTitle {
            get {
                return ResourceManager.GetString("TehillimTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to היום.
        /// </summary>
        public static string TehillimTodayTitle {
            get {
                return ResourceManager.GetString("TehillimTodayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפילת הדרך.
        /// </summary>
        public static string TfilatHaderechTitle {
            get {
                return ResourceManager.GetString("TfilatHaderechTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפילות השחר.
        /// </summary>
        public static string TfilotHashacharTitle {
            get {
                return ResourceManager.GetString("TfilotHashacharTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כהה.
        /// </summary>
        public static string ThemeNameDark {
            get {
                return ResourceManager.GetString("ThemeNameDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כמו מערכת ההפעלה.
        /// </summary>
        public static string ThemeNameFromOS {
            get {
                return ResourceManager.GetString("ThemeNameFromOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בהירה.
        /// </summary>
        public static string ThemeNameLight {
            get {
                return ResourceManager.GetString("ThemeNameLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערכת נושא:.
        /// </summary>
        public static string ThemeSettingLabel {
            get {
                return ResourceManager.GetString("ThemeSettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שלישי.
        /// </summary>
        public static string ThirdTorahReaderTitle {
            get {
                return ResourceManager.GetString("ThirdTorahReaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שלוש פעמים: {0}.
        /// </summary>
        public static string ThreeTimesInst_F0 {
            get {
                return ResourceManager.GetString("ThreeTimesInst_F0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיטת חישוב זמנים:.
        /// </summary>
        public static string TimeCalcMethodLabel {
            get {
                return ResourceManager.GetString("TimeCalcMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שים לב שהיום תשעה באב, והתפילה המופיעה כאן אינה מלאה..
        /// </summary>
        public static string TishaBeavMessage {
            get {
                return ResourceManager.GetString("TishaBeavMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כלים.
        /// </summary>
        public static string ToolsTitle {
            get {
                return ResourceManager.GetString("ToolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוצאת ספר תורה.
        /// </summary>
        public static string TorahBookHotzaaTitle {
            get {
                return ResourceManager.GetString("TorahBookHotzaaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכנסת ספר תורה.
        /// </summary>
        public static string TorahBookReplacingTitle {
            get {
                return ResourceManager.GetString("TorahBookReplacingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קריאת התורה וההפטרה.
        /// </summary>
        public static string TorahReadingAndHaftarahTitle {
            get {
                return ResourceManager.GetString("TorahReadingAndHaftarahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קריאת התורה.
        /// </summary>
        public static string TorahReadingTitle {
            get {
                return ResourceManager.GetString("TorahReadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מ-.
        /// </summary>
        public static string UnitConversionFromLabel {
            get {
                return ResourceManager.GetString("UnitConversionFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המרת מידות.
        /// </summary>
        public static string UnitConversionTitle {
            get {
                return ResourceManager.GetString("UnitConversionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ל-.
        /// </summary>
        public static string UnitConversionToLabel {
            get {
                return ResourceManager.GetString("UnitConversionToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ממיר מידות.
        /// </summary>
        public static string UnitConverterTitle {
            get {
                return ResourceManager.GetString("UnitConverterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חישובי הזמנים יתבצעו לפי הדינים של מי שגר בחו&quot;ל.
        /// </summary>
        public static string UseChulSettingDescription {
            get {
                return ResourceManager.GetString("UseChulSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השתמש בדיני הדרים בחו&quot;ל.
        /// </summary>
        public static string UseChulSettingTitle {
            get {
                return ResourceManager.GetString("UseChulSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השתמש ברקע בהיר.
        /// </summary>
        public static string UseLightBackgroundSettingTitle {
            get {
                return ResourceManager.GetString("UseLightBackgroundSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בעזרת המיקום יחושבו רק זמני היום, זמני התפילות, כיוון התפילה וצאת הכוכבים. המיקומים שלך לא ישמרו..
        /// </summary>
        public static string UseLocationPrivacyPolicy {
            get {
                return ResourceManager.GetString("UseLocationPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השתמש במיקום.
        /// </summary>
        public static string UseLocationSettingTitle {
            get {
                return ResourceManager.GetString("UseLocationSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ותתפלל חנה.
        /// </summary>
        public static string VatitpallelChannahTitle {
            get {
                return ResourceManager.GetString("VatitpallelChannahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בזמן עצירת גשמים.
        /// </summary>
        public static string VeAnenuTitle {
            get {
                return ResourceManager.GetString("VeAnenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לפני תפילת ערבית.
        /// </summary>
        public static string VersesBeforeArvitTitle {
            get {
                return ResourceManager.GetString("VersesBeforeArvitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לפני תפילת מנחה.
        /// </summary>
        public static string VersesBeforeMinchaTitle {
            get {
                return ResourceManager.GetString("VersesBeforeMinchaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נפח.
        /// </summary>
        public static string VolumeTitle {
            get {
                return ResourceManager.GetString("VolumeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משקל.
        /// </summary>
        public static string WeightTitle {
            get {
                return ResourceManager.GetString("WeightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחוה&quot;מ פסח.
        /// </summary>
        public static string YaalehVeyavoPesachTitle {
            get {
                return ResourceManager.GetString("YaalehVeyavoPesachTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בראש חודש.
        /// </summary>
        public static string YaalehVeyavoRoshHodeshTitle {
            get {
                return ResourceManager.GetString("YaalehVeyavoRoshHodeshTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחוה&quot;מ סוכות.
        /// </summary>
        public static string YaalehVeyavoSukkotTitle {
            get {
                return ResourceManager.GetString("YaalehVeyavoSukkotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ישתבח.
        /// </summary>
        public static string YishtabachTitle {
            get {
                return ResourceManager.GetString("YishtabachTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הודאה.
        /// </summary>
        public static string YomHaazmautARvitHodaaTitle {
            get {
                return ResourceManager.GetString("YomHaazmautARvitHodaaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זימון.
        /// </summary>
        public static string ZimmunTitle {
            get {
                return ResourceManager.GetString("ZimmunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לבישת ציצית.
        /// </summary>
        public static string ZizitWearingTitle {
            get {
                return ResourceManager.GetString("ZizitWearingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to היום.
        /// </summary>
        public static string ZmaneyHayom {
            get {
                return ResourceManager.GetString("ZmaneyHayom", resourceCulture);
            }
        }
    }
}
