//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrayPal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Leviticus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Leviticus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrayPal.Resources.Leviticus", typeof(Leviticus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיִּקְרָ֖א אֶל־מֹשֶׁ֑ה וַיְדַבֵּ֤ר יְהוָה֙ אֵלָ֔יו מֵאֹ֥הֶל מוֹעֵ֖ד לֵאמֹֽר׃&amp;דַּבֵּ֞ר אֶל־בְּנֵ֤י יִשְׂרָאֵל֙ וְאָֽמַרְתָּ֣ אֲלֵהֶ֔ם אָדָ֗ם כִּֽי־יַקְרִ֥יב מִכֶּ֛ם קָרְבָּ֖ן לַֽיהוָ֑ה מִן־הַבְּהֵמָ֗ה מִן־הַבָּקָר֙ וּמִן־הַצֹּ֔אן תַּקְרִ֖יבוּ אֶת־קָרְבַּנְכֶֽם׃&amp;אִם־עֹלָ֤ה קָרְבָּנוֹ֙ מִן־הַבָּקָ֔ר זָכָ֥ר תָּמִ֖ים יַקְרִיבֶ֑נּוּ אֶל־פֶּ֜תַח אֹ֤הֶל מוֹעֵד֙ יַקְרִ֣יב אֹת֔וֹ לִרְצֹנ֖וֹ לִפְנֵ֥י יְהוָֽה׃&amp;וְסָמַ֣ךְ יָד֔וֹ עַ֖ל רֹ֣אשׁ הָֽעֹלָ֑ה וְנִרְצָ֥ה ל֖וֹ לְכַפֵּ֥ר עָלָֽיו׃&amp;וְשָׁחַ֛ט אֶת־בֶּ֥ן הַבָּקָ֖ר לִפְנ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter1 {
            get {
                return ResourceManager.GetString("Chapter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיִּקְח֣וּ בְנֵֽי־אַ֠הֲרֹן נָדָ֨ב וַֽאֲבִיה֜וּא אִ֣ישׁ מַחְתָּת֗וֹ וַיִּתְּנ֤וּ בָהֵן֙ אֵ֔שׁ וַיָּשִׂ֥ימוּ עָלֶ֖יהָ קְטֹ֑רֶת וַיַּקְרִ֜יבוּ לִפְנֵ֤י יְהוָה֙ אֵ֣שׁ זָרָ֔ה אֲשֶׁ֧ר לֹ֦א צִוָּ֖ה אֹתָֽם׃&amp;וַתֵּ֥צֵא אֵ֛שׁ מִלִּפְנֵ֥י יְהוָ֖ה וַתֹּ֣אכַל אוֹתָ֑ם וַיָּמֻ֖תוּ לִפְנֵ֥י יְהוָֽה׃&amp;וַיֹּ֨אמֶר מֹשֶׁ֜ה אֶֽל־אַהֲרֹ֗ן הוּא֩ אֲשֶׁר־דִּבֶּ֨ר יְהוָ֤ה ׀ לֵאמֹר֙ בִּקְרֹבַ֣י אֶקָּדֵ֔שׁ וְעַל־פְּנֵ֥י כָל־הָעָ֖ם אֶכָּבֵ֑ד וַיִּדֹּ֖ם אַֽהֲרֹֽן׃&amp;וַיִּקְרָ֣א מֹשֶׁ֗ה אֶל־מִֽישָׁאֵל֙ וְאֶ֣ל אֶלְצָפָ֔ן בְּנֵ֥י עֻזִּיאֵ֖ל ד [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter10 {
            get {
                return ResourceManager.GetString("Chapter10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֧ר יְהוָ֛ה אֶל־מֹשֶׁ֥ה וְאֶֽל־אַהֲרֹ֖ן לֵאמֹ֥ר אֲלֵהֶֽם׃&amp;דַּבְּר֛וּ אֶל־בְּנֵ֥י יִשְׂרָאֵ֖ל לֵאמֹ֑ר זֹ֤את הַֽחַיָּה֙ אֲשֶׁ֣ר תֹּֽאכְל֔וּ מִכָּל־הַבְּהֵמָ֖ה אֲשֶׁ֥ר עַל־הָאָֽרֶץ׃&amp;כֹּ֣ל ׀ מַפְרֶ֣סֶת פַּרְסָ֗ה וְשֹׁסַ֤עַת שֶׁ֨סַע֙ פְּרָסֹ֔ת מַֽעֲלַ֥ת גֵּרָ֖ה בַּבְּהֵמָ֑ה אֹתָ֖הּ תֹּאכֵֽלוּ׃&amp;אַ֤ךְ אֶת־זֶה֙ לֹ֣א תֹֽאכְל֔וּ מִֽמַּעֲלֵי֙ הַגֵּרָ֔ה וּמִמַּפְרִסֵ֖י הַפַּרְסָ֑ה אֶֽת־הַ֠גָּמָל כִּֽי־מַעֲלֵ֨ה גֵרָ֜ה ה֗וּא וּפַרְסָה֙ אֵינֶ֣נּוּ מַפְרִ֔יס טָמֵ֥א ה֖וּא לָכֶֽם׃&amp;וְאֶת־הַשָּׁפָ֗ן כִּֽי־מַעֲלֵ֤ה גֵרָ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter11 {
            get {
                return ResourceManager.GetString("Chapter11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֥ר יְהוָ֖ה אֶל־מֹשֶׁ֥ה לֵּאמֹֽר׃&amp;דַּבֵּ֞ר אֶל־בְּנֵ֤י יִשְׂרָאֵל֙ לֵאמֹ֔ר אִשָּׁה֙ כִּ֣י תַזְרִ֔יעַ וְיָֽלְדָ֖ה זָכָ֑ר וְטָֽמְאָה֙ שִׁבְעַ֣ת יָמִ֔ים כִּימֵ֛י נִדַּ֥ת דְּו‍ֹתָ֖הּ תִּטְמָֽא׃&amp;וּבַיּ֖וֹם הַשְּׁמִינִ֑י יִמּ֖וֹל בְּשַׂ֥ר עָרְלָתֽוֹ׃&amp;וּשְׁלֹשִׁ֥ים יוֹם֙ וּשְׁלֹ֣שֶׁת יָמִ֔ים תֵּשֵׁ֖ב בִּדְמֵ֣י טָֽהֳרָ֑ה בְּכָל־קֹ֣דֶשׁ לֹֽא־תִגָּ֗ע וְאֶל־הַמִּקְדָּשׁ֙ לֹ֣א תָבֹ֔א עַד־מְלֹ֖את יְמֵ֥י טָֽהֳרָֽהּ׃&amp;וְאִם־נְקֵבָ֣ה תֵלֵ֔ד וְטָֽמְאָ֥ה שְׁבֻעַ֖יִם כְּנִדָּתָ֑הּ וְשִׁשִּׁ֥ים יוֹם֙ וְשֵׁ֣שֶׁת יָמִ֔ים  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter12 {
            get {
                return ResourceManager.GetString("Chapter12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֣ר יְהוָ֔ה אֶל־מֹשֶׁ֥ה וְאֶֽל־אַהֲרֹ֖ן לֵאמֹֽר׃&amp;אָדָ֗ם כִּֽי־יִהְיֶ֤ה בְעוֹר־בְּשָׂרוֹ֙ שְׂאֵ֤ת אֽוֹ־סַפַּ֨חַת֙ א֣וֹ בַהֶ֔רֶת וְהָיָ֥ה בְעוֹר־בְּשָׂר֖וֹ לְנֶ֣גַע צָרָ֑עַת וְהוּבָא֙ אֶל־אַֽהֲרֹ֣ן הַכֹּהֵ֔ן א֛וֹ אֶל־אַחַ֥ד מִבָּנָ֖יו הַכֹּֽהֲנִֽים׃&amp;וְרָאָ֣ה הַכֹּהֵ֣ן אֶת־הַנֶּ֣גַע בְּעֽוֹר־הַ֠בָּשָׂר וְשֵׂעָ֨ר בַּנֶּ֜גַע הָפַ֣ךְ ׀ לָבָ֗ן וּמַרְאֵ֤ה הַנֶּ֨גַע֙ עָמֹק֙ מֵע֣וֹר בְּשָׂר֔וֹ נֶ֥גַע צָרַ֖עַת ה֑וּא וְרָאָ֥הוּ הַכֹּהֵ֖ן וְטִמֵּ֥א אֹתֽוֹ׃&amp;וְאִם־בַּהֶרֶת֩ לְבָנָ֨ה הִ֜וא בְּע֣וֹר בְּשָׂר֗וֹ וְעָמ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter13 {
            get {
                return ResourceManager.GetString("Chapter13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֥ר יְהוָ֖ה אֶל־מֹשֶׁ֥ה לֵּאמֹֽר׃&amp;זֹ֤את תִּֽהְיֶה֙ תּוֹרַ֣ת הַמְּצֹרָ֔ע בְּי֖וֹם טָֽהֳרָת֑וֹ וְהוּבָ֖א אֶל־הַכֹּהֵֽן׃&amp;וְיָצָא֙ הַכֹּהֵ֔ן אֶל־מִח֖וּץ לַֽמַּחֲנֶ֑ה וְרָאָה֙ הַכֹּהֵ֔ן וְהִנֵּ֛ה נִרְפָּ֥א נֶֽגַע־הַצָּרַ֖עַת מִן־הַצָּרֽוּעַ׃&amp;וְצִוָּה֙ הַכֹּהֵ֔ן וְלָקַ֧ח לַמִּטַּהֵ֛ר שְׁתֵּֽי־צִפֳּרִ֥ים חַיּ֖וֹת טְהֹר֑וֹת וְעֵ֣ץ אֶ֔רֶז וּשְׁנִ֥י תוֹלַ֖עַת וְאֵזֹֽב׃&amp;וְצִוָּה֙ הַכֹּהֵ֔ן וְשָׁחַ֖ט אֶת־הַצִּפּ֣וֹר הָֽאֶחָ֑ת אֶל־כְּלִי־חֶ֖רֶשׂ עַל־מַ֥יִם חַיִּֽים׃&amp;אֶת־הַצִּפֹּ֤ר הַֽחַיָּה֙ יִקַּ֣ח אֹתָ֔הּ וְאֶ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter14 {
            get {
                return ResourceManager.GetString("Chapter14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֣ר יְהוָ֔ה אֶל־מֹשֶׁ֥ה וְאֶֽל־אַהֲרֹ֖ן לֵאמֹֽר׃&amp;דַּבְּרוּ֙ אֶל־בְּנֵ֣י יִשְׂרָאֵ֔ל וַֽאֲמַרְתֶּ֖ם אֲלֵהֶ֑ם אִ֣ישׁ אִ֗ישׁ כִּ֤י יִֽהְיֶה֙ זָ֣ב מִבְּשָׂר֔וֹ זוֹב֖וֹ טָמֵ֥א הֽוּא׃&amp;וְזֹ֛את תִּֽהְיֶ֥ה טֻמְאָת֖וֹ בְּזוֹב֑וֹ רָ֣ר בְּשָׂר֞וֹ אֶת־זוֹב֗וֹ אֽוֹ־הֶחְתִּ֤ים בְּשָׂרוֹ֙ מִזּוֹב֔וֹ טֻמְאָת֖וֹ הִֽוא׃&amp;כָּל־הַמִּשְׁכָּ֗ב אֲשֶׁ֨ר יִשְׁכַּ֥ב עָלָ֛יו הַזָּ֖ב יִטְמָ֑א וְכָֽל־הַכְּלִ֛י אֲשֶׁר־יֵשֵׁ֥ב עָלָ֖יו יִטְמָֽא׃&amp;וְאִ֕ישׁ אֲשֶׁ֥ר יִגַּ֖ע בְּמִשְׁכָּב֑וֹ יְכַבֵּ֧ס בְּגָדָ֛יו וְרָחַ֥ץ בַּמַּ֖יִם וְטָמֵ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter15 {
            get {
                return ResourceManager.GetString("Chapter15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֤ר יְהוָה֙ אֶל־מֹשֶׁ֔ה אַֽחֲרֵ֣י מ֔וֹת שְׁנֵ֖י בְּנֵ֣י אַֽהֲרֹ֑ן בְּקָרְבָתָ֥ם לִפְנֵי־יְהוָ֖ה וַיָּמֻֽתוּ׃&amp;וַיֹּ֨אמֶר יְהוָ֜ה אֶל־מֹשֶׁ֗ה דַּבֵּר֮ אֶל־אַֽהֲרֹ֣ן אָחִיךָ֒ וְאַל־יָבֹ֤א בְכָל־עֵת֙ אֶל־הַקֹּ֔דֶשׁ מִבֵּ֖ית לַפָּרֹ֑כֶת אֶל־פְּנֵ֨י הַכַּפֹּ֜רֶת אֲשֶׁ֤ר עַל־הָֽאָרֹן֙ וְלֹ֣א יָמ֔וּת כִּ֚י בֶּֽעָנָ֔ן אֵֽרָאֶ֖ה עַל־הַכַּפֹּֽרֶת׃&amp;בְּזֹ֛את יָבֹ֥א אַֽהֲרֹ֖ן אֶל־הַקֹּ֑דֶשׁ בְּפַ֧ר בֶּן־בָּקָ֛ר לְחַטָּ֖את וְאַ֥יִל לְעֹלָֽה׃&amp;כְּתֹֽנֶת־בַּ֨ד קֹ֜דֶשׁ יִלְבָּ֗שׁ וּמִֽכְנְסֵי־בַד֮ יִֽהְי֣וּ עַל־בְּשָׂ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter16 {
            get {
                return ResourceManager.GetString("Chapter16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֥ר יְהוָ֖ה אֶל־מֹשֶׁ֥ה לֵּאמֹֽר׃&amp;דַּבֵּ֨ר אֶֽל־אַהֲרֹ֜ן וְאֶל־בָּנָ֗יו וְאֶל֙ כָּל־בְּנֵ֣י יִשְׂרָאֵ֔ל וְאָֽמַרְתָּ֖ אֲלֵיהֶ֑ם זֶ֣ה הַדָּבָ֔ר אֲשֶׁר־צִוָּ֥ה יְהוָ֖ה לֵאמֹֽר׃&amp;אִ֥ישׁ אִישׁ֙ מִבֵּ֣ית יִשְׂרָאֵ֔ל אֲשֶׁ֨ר יִשְׁחַ֜ט שׁ֥וֹר אוֹ־כֶ֛שֶׂב אוֹ־עֵ֖ז בַּֽמַּחֲנֶ֑ה א֚וֹ אֲשֶׁ֣ר יִשְׁחַ֔ט מִח֖וּץ לַֽמַּחֲנֶֽה׃&amp;וְאֶל־פֶּ֜תַח אֹ֣הֶל מוֹעֵד֮ לֹ֣א הֱבִיאוֹ֒ לְהַקְרִ֤יב קָרְבָּן֙ לַֽיהוָ֔ה לִפְנֵ֖י מִשְׁכַּ֣ן יְהוָ֑ה דָּ֣ם יֵֽחָשֵׁ֞ב לָאִ֤ישׁ הַהוּא֙ דָּ֣ם שָׁפָ֔ךְ וְנִכְרַ֛ת הָאִ֥ישׁ הַה֖וּא מִקֶּ֥רֶ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter17 {
            get {
                return ResourceManager.GetString("Chapter17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֥ר יְהוָ֖ה אֶל־מֹשֶׁ֥ה לֵּאמֹֽר׃&amp;דַּבֵּר֙ אֶל־בְּנֵ֣י יִשְׂרָאֵ֔ל וְאָֽמַרְתָּ֖ אֲלֵהֶ֑ם אֲנִ֖י יְהוָ֥ה אֱלֹֽהֵיכֶֽם׃&amp;כְּמַֽעֲשֵׂ֧ה אֶֽרֶץ־מִצְרַ֛יִם אֲשֶׁ֥ר יְשַׁבְתֶּם־בָּ֖הּ לֹ֣א תַֽעֲשׂ֑וּ וּכְמַֽעֲשֵׂ֣ה אֶֽרֶץ־כְּנַ֡עַן אֲשֶׁ֣ר אֲנִי֩ מֵבִ֨יא אֶתְכֶ֥ם שָׁ֨מָּה֙ לֹ֣א תַֽעֲשׂ֔וּ וּבְחֻקֹּֽתֵיהֶ֖ם לֹ֥א תֵלֵֽכוּ׃&amp;אֶת־מִשְׁפָּטַ֧י תַּֽעֲשׂ֛וּ וְאֶת־חֻקֹּתַ֥י תִּשְׁמְר֖וּ לָלֶ֣כֶת בָּהֶ֑ם אֲנִ֖י יְהוָ֥ה אֱלֹֽהֵיכֶֽם׃&amp;וּשְׁמַרְתֶּ֤ם אֶת־חֻקֹּתַי֙ וְאֶת־מִשְׁפָּטַ֔י אֲשֶׁ֨ר יַֽעֲשֶׂ֥ה אֹתָ֛ם הָֽאָדָ֖ם [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter18 {
            get {
                return ResourceManager.GetString("Chapter18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֥ר יְהוָ֖ה אֶל־מֹשֶׁ֥ה לֵּאמֹֽר׃&amp;דַּבֵּ֞ר אֶל־כָּל־עֲדַ֧ת בְּנֵֽי־יִשְׂרָאֵ֛ל וְאָֽמַרְתָּ֥ אֲלֵהֶ֖ם קְדֹשִׁ֣ים תִּֽהְי֑וּ כִּ֣י קָד֔וֹשׁ אֲנִ֖י יְהוָ֥ה אֱלֹֽהֵיכֶֽם׃&amp;אִ֣ישׁ אִמּ֤וֹ וְאָבִיו֙ תִּירָ֔אוּ וְאֶת־שַׁבְּתֹתַ֖י תִּשְׁמֹ֑רוּ אֲנִ֖י יְהוָ֥ה אֱלֹֽהֵיכֶֽם׃&amp;אַל־תִּפְנוּ֙ אֶל־הָ֣אֱלִילִ֔ם וֵֽאלֹהֵי֙ מַסֵּכָ֔ה לֹ֥א תַֽעֲשׂ֖וּ לָכֶ֑ם אֲנִ֖י יְהוָ֥ה אֱלֹֽהֵיכֶֽם׃&amp;וְכִ֧י תִזְבְּח֛וּ זֶ֥בַח שְׁלָמִ֖ים לַֽיהוָ֑ה לִֽרְצֹנְכֶ֖ם תִּזְבָּחֻֽהוּ׃&amp;בְּי֧וֹם זִבְחֲכֶ֛ם יֵֽאָכֵ֖ל וּמִֽמָּחֳרָ֑ת וְהַנּוֹתָר֙  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter19 {
            get {
                return ResourceManager.GetString("Chapter19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וְנֶ֗פֶשׁ כִּֽי־תַקְרִ֞יב קָרְבַּ֤ן מִנְחָה֙ לַֽיהוָ֔ה סֹ֖לֶת יִֽהְיֶ֣ה קָרְבָּנ֑וֹ וְיָצַ֤ק עָלֶ֨יהָ֙ שֶׁ֔מֶן וְנָתַ֥ן עָלֶ֖יהָ לְבֹנָֽה׃&amp;וֶֽהֱבִיאָ֗הּ אֶל־בְּנֵ֣י אַֽהֲרֹן֮ הַכֹּֽהֲנִים֒ וְקָמַ֨ץ מִשָּׁ֜ם מְלֹ֣א קֻמְצ֗וֹ מִסָּלְתָּהּ֙ וּמִשַּׁמְנָ֔הּ עַ֖ל כָּל־לְבֹֽנָתָ֑הּ וְהִקְטִ֨יר הַכֹּהֵ֜ן אֶת־אַזְכָּֽרָתָהּ֙ הַמִּזְבֵּ֔חָה אִשֵּׁ֛ה רֵ֥יחַ נִיחֹ֖חַ לַֽיהוָֽה׃&amp;וְהַנּוֹתֶ֨רֶת֙ מִן־הַמִּנְחָ֔ה לְאַֽהֲרֹ֖ן וּלְבָנָ֑יו קֹ֥דֶשׁ קָֽדָשִׁ֖ים מֵֽאִשֵּׁ֥י יְהוָֽה׃&amp;וְכִ֥י תַקְרִ֛ב קָרְבַּ֥ן מִנְחָ֖ה מַֽאֲפֵ֣ה ת [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter2 {
            get {
                return ResourceManager.GetString("Chapter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֥ר יְהוָ֖ה אֶל־מֹשֶׁ֥ה לֵּאמֹֽר׃&amp;וְאֶל־בְּנֵ֣י יִשְׂרָאֵל֮ תֹּאמַר֒ אִ֣ישׁ אִישׁ֩ מִבְּנֵ֨י יִשְׂרָאֵ֜ל וּמִן־הַגֵּ֣ר ׀ הַגָּ֣ר בְּיִשְׂרָאֵ֗ל אֲשֶׁ֨ר יִתֵּ֧ן מִזַּרְע֛וֹ לַמֹּ֖לֶךְ מ֣וֹת יוּמָ֑ת עַ֥ם הָאָ֖רֶץ יִרְגְּמֻ֥הוּ בָאָֽבֶן׃&amp;וַֽאֲנִ֞י אֶתֵּ֤ן אֶת־פָּנַי֙ בָּאִ֣ישׁ הַה֔וּא וְהִכְרַתִּ֥י אֹת֖וֹ מִקֶּ֣רֶב עַמּ֑וֹ כִּ֤י מִזַּרְעוֹ֙ נָתַ֣ן לַמֹּ֔לֶךְ לְמַ֗עַן טַמֵּא֙ אֶת־מִקְדָּשִׁ֔י וּלְחַלֵּ֖ל אֶת־שֵׁ֥ם קָדְשִֽׁי׃&amp;וְאִ֡ם הַעְלֵ֣ם יַעְלִימֽוּ֩ עַ֨ם הָאָ֜רֶץ אֶת־עֵֽינֵיהֶם֙ מִן־הָאִ֣ישׁ הַה֔וּא [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter20 {
            get {
                return ResourceManager.GetString("Chapter20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיֹּ֤אמֶר יְהוָה֙ אֶל־מֹשֶׁ֔ה אֱמֹ֥ר אֶל־הַכֹּֽהֲנִ֖ים בְּנֵ֣י אַֽהֲרֹ֑ן וְאָֽמַרְתָּ֣ אֲלֵהֶ֔ם לְנֶ֥פֶשׁ לֹֽא־יִטַּמָּ֖א בְּעַמָּֽיו׃&amp;כִּ֚י אִם־לִשְׁאֵר֔וֹ הַקָּרֹ֖ב אֵלָ֑יו לְאִמּ֣וֹ וּלְאָבִ֔יו וְלִבְנ֥וֹ וּלְבִתּ֖וֹ וּלְאָחִֽיו׃&amp;וְלַֽאֲחֹת֤וֹ הַבְּתוּלָה֙ הַקְּרוֹבָ֣ה אֵלָ֔יו אֲשֶׁ֥ר לֹֽא־הָיְתָ֖ה לְאִ֑ישׁ לָ֖הּ יִטַּמָּֽא׃&amp;לֹ֥א יִטַּמָּ֖א בַּ֣עַל בְּעַמָּ֑יו לְהֵ֖חַלּֽוֹ׃&amp;לֹֽא־יקרחה (יִקְרְח֤וּ) קָרְחָה֙ בְּרֹאשָׁ֔ם וּפְאַ֥ת זְקָנָ֖ם לֹ֣א יְגַלֵּ֑חוּ וּבִ֨בְשָׂרָ֔ם לֹ֥א יִשְׂרְט֖וּ שָׂרָֽטֶת׃&amp;קְדֹשִׁ֤ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter21 {
            get {
                return ResourceManager.GetString("Chapter21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֥ר יְהוָ֖ה אֶל־מֹשֶׁ֥ה לֵּאמֹֽר׃&amp;דַּבֵּ֨ר אֶֽל־אַהֲרֹ֜ן וְאֶל־בָּנָ֗יו וְיִנָּֽזְרוּ֙ מִקָּדְשֵׁ֣י בְנֵֽי־יִשְׂרָאֵ֔ל וְלֹ֥א יְחַלְּל֖וּ אֶת־שֵׁ֣ם קָדְשִׁ֑י אֲשֶׁ֨ר הֵ֧ם מַקְדִּשִׁ֛ים לִ֖י אֲנִ֥י יְהוָֽה׃&amp;אֱמֹ֣ר אֲלֵהֶ֗ם לְדֹרֹ֨תֵיכֶ֜ם כָּל־אִ֣ישׁ ׀ אֲשֶׁר־יִקְרַ֣ב מִכָּל־זַרְעֲכֶ֗ם אֶל־הַקֳּדָשִׁים֙ אֲשֶׁ֨ר יַקְדִּ֤ישׁוּ בְנֵֽי־יִשְׂרָאֵל֙ לַֽיהוָ֔ה וְטֻמְאָת֖וֹ עָלָ֑יו וְנִכְרְתָ֞ה הַנֶּ֧פֶשׁ הַהִ֛וא מִלְּפָנַ֖י אֲנִ֥י יְהוָֽה׃&amp;אִ֣ישׁ אִ֞ישׁ מִזֶּ֣רַע אַֽהֲרֹ֗ן וְה֤וּא צָר֨וּעַ֙ א֣וֹ זָ֔ב בַּקֳּד [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter22 {
            get {
                return ResourceManager.GetString("Chapter22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֥ר יְהוָ֖ה אֶל־מֹשֶׁ֥ה לֵּאמֹֽר׃&amp;דַּבֵּ֞ר אֶל־בְּנֵ֤י יִשְׂרָאֵל֙ וְאָֽמַרְתָּ֣ אֲלֵהֶ֔ם מֽוֹעֲדֵ֣י יְהוָ֔ה אֲשֶׁר־תִּקְרְא֥וּ אֹתָ֖ם מִקְרָאֵ֣י קֹ֑דֶשׁ אֵ֥לֶּה הֵ֖ם מֽוֹעֲדָֽי׃&amp;שֵׁ֣שֶׁת יָמִים֮ תֵּֽעָשֶׂ֣ה מְלָאכָה֒ וּבַיּ֣וֹם הַשְּׁבִיעִ֗י שַׁבַּ֤ת שַׁבָּתוֹן֙ מִקְרָא־קֹ֔דֶשׁ כָּל־מְלָאכָ֖ה לֹ֣א תַֽעֲשׂ֑וּ שַׁבָּ֥ת הִוא֙ לַֽיהוָ֔ה בְּכֹ֖ל מוֹשְׁבֹֽתֵיכֶֽם׃
        ///&amp;אֵ֚לֶּה מֽוֹעֲדֵ֣י יְהוָ֔ה מִקְרָאֵ֖י קֹ֑דֶשׁ אֲשֶׁר־תִּקְרְא֥וּ אֹתָ֖ם בְּמֽוֹעֲדָֽם׃&amp;בַּחֹ֣דֶשׁ הָֽרִאשׁ֗וֹן בְּאַרְבָּעָ֥ה עָשָׂ֛ר לַחֹ֖ד [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter23 {
            get {
                return ResourceManager.GetString("Chapter23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֥ר יְהוָ֖ה אֶל־מֹשֶׁ֥ה לֵּאמֹֽר׃&amp;צַ֞ו אֶת־בְּנֵ֣י יִשְׂרָאֵ֗ל וְיִקְח֨וּ אֵלֶ֜יךָ שֶׁ֣מֶן זַ֥יִת זָ֛ךְ כָּתִ֖ית לַמָּא֑וֹר לְהַֽעֲלֹ֥ת נֵ֖ר תָּמִֽיד׃&amp;מִחוּץ֩ לְפָרֹ֨כֶת הָֽעֵדֻ֜ת בְּאֹ֣הֶל מוֹעֵ֗ד יַֽעֲרֹךְ֩ אֹת֨וֹ אַֽהֲרֹ֜ן מֵעֶ֧רֶב עַד־בֹּ֛קֶר לִפְנֵ֥י יְהוָ֖ה תָּמִ֑יד חֻקַּ֥ת עוֹלָ֖ם לְדֹרֹֽתֵיכֶֽם׃&amp;עַ֚ל הַמְּנֹרָ֣ה הַטְּהֹרָ֔ה יַֽעֲרֹ֖ךְ אֶת־הַנֵּר֑וֹת לִפְנֵ֥י יְהוָ֖ה תָּמִֽיד׃
        ///&amp;וְלָֽקַחְתָּ֣ סֹ֔לֶת וְאָֽפִיתָ֣ אֹתָ֔הּ שְׁתֵּ֥ים עֶשְׂרֵ֖ה חַלּ֑וֹת שְׁנֵי֙ עֶשְׂרֹנִ֔ים יִֽהְיֶ֖ה הַֽחַלָּ֥ה הָֽ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter24 {
            get {
                return ResourceManager.GetString("Chapter24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֤ר יְהוָה֙ אֶל־מֹשֶׁ֔ה בְּהַ֥ר סִינַ֖י לֵאמֹֽר׃&amp;דַּבֵּ֞ר אֶל־בְּנֵ֤י יִשְׂרָאֵל֙ וְאָֽמַרְתָּ֣ אֲלֵהֶ֔ם כִּ֤י תָבֹ֨אוּ֙ אֶל־הָאָ֔רֶץ אֲשֶׁ֥ר אֲנִ֖י נֹתֵ֣ן לָכֶ֑ם וְשָֽׁבְתָ֣ה הָאָ֔רֶץ שַׁבָּ֖ת לַֽיהוָֽה׃&amp;שֵׁ֤שׁ שָׁנִים֙ תִּזְרַ֣ע שָׂדֶ֔ךָ וְשֵׁ֥שׁ שָׁנִ֖ים תִּזְמֹ֣ר כַּרְמֶ֑ךָ וְאָֽסַפְתָּ֖ אֶת־תְּבֽוּאָתָֽהּ׃&amp;וּבַשָּׁנָ֣ה הַשְּׁבִיעִ֗ת שַׁבַּ֤ת שַׁבָּתוֹן֙ יִֽהְיֶ֣ה לָאָ֔רֶץ שַׁבָּ֖ת לַֽיהוָ֑ה שָֽׂדְךָ֙ לֹ֣א תִזְרָ֔ע וְכַרְמְךָ֖ לֹ֥א תִזְמֹֽר׃&amp;אֵ֣ת סְפִ֤יחַ קְצִֽירְךָ֙ לֹ֣א תִקְצ֔וֹר וְאֶת־עִנְּבֵ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter25 {
            get {
                return ResourceManager.GetString("Chapter25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לֹֽא־תַעֲשׂ֨וּ לָכֶ֜ם אֱלִילִ֗ם וּפֶ֤סֶל וּמַצֵּבָה֙ לֹֽא־תָקִ֣ימוּ לָכֶ֔ם וְאֶ֣בֶן מַשְׂכִּ֗ית לֹ֤א תִתְּנוּ֙ בְּאַרְצְכֶ֔ם לְהִֽשְׁתַּחֲו֖‍ֹת עָלֶ֑יהָ כִּ֛י אֲנִ֥י יְהוָ֖ה אֱלֹֽהֵיכֶֽם׃&amp;אֶת־שַׁבְּתֹתַ֣י תִּשְׁמֹ֔רוּ וּמִקְדָּשִׁ֖י תִּירָ֑אוּ אֲנִ֖י יְהוָֽה׃
        ///&amp;אִם־בְּחֻקֹּתַ֖י תֵּלֵ֑כוּ וְאֶת־מִצְו‍ֹתַ֣י תִּשְׁמְר֔וּ וַֽעֲשִׂיתֶ֖ם אֹתָֽם׃&amp;וְנָֽתַתִּ֥י גִשְׁמֵיכֶ֖ם בְּעִתָּ֑ם וְנָֽתְנָ֤ה הָאָ֨רֶץ֙ יְבוּלָ֔הּ וְעֵ֥ץ הַשָּׂדֶ֖ה יִתֵּ֥ן פִּרְיֽוֹ׃&amp;וְהִשִּׂ֨יג לָכֶ֥ם דַּ֨יִשׁ֙ אֶת־בָּצִ֔יר וּבָצִ֖יר יַשִּׂ֣יג א [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter26 {
            get {
                return ResourceManager.GetString("Chapter26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֥ר יְהוָ֖ה אֶל־מֹשֶׁ֥ה לֵּאמֹֽר׃&amp;דַּבֵּ֞ר אֶל־בְּנֵ֤י יִשְׂרָאֵל֙ וְאָֽמַרְתָּ֣ אֲלֵהֶ֔ם אִ֕ישׁ כִּ֥י יַפְלִ֖א נֶ֑דֶר בְּעֶרְכְּךָ֥ נְפָשֹׁ֖ת לַֽיהוָֽה׃&amp;וְהָיָ֤ה עֶרְכְּךָ֙ הַזָּכָ֔ר מִבֶּן֙ עֶשְׂרִ֣ים שָׁנָ֔ה וְעַ֖ד בֶּן־שִׁשִּׁ֣ים שָׁנָ֑ה וְהָיָ֣ה עֶרְכְּךָ֗ חֲמִשִּׁ֛ים שֶׁ֥קֶל כֶּ֖סֶף בְּשֶׁ֥קֶל הַקֹּֽדֶשׁ׃&amp;וְאִם־נְקֵבָ֖ה הִ֑וא וְהָיָ֥ה עֶרְכְּךָ֖ שְׁלֹשִׁ֥ים שָֽׁקֶל׃&amp;וְאִ֨ם מִבֶּן־חָמֵ֜שׁ שָׁנִ֗ים וְעַד֙ בֶּן־עֶשְׂרִ֣ים שָׁנָ֔ה וְהָיָ֧ה עֶרְכְּךָ֛ הַזָּכָ֖ר עֶשְׂרִ֣ים שְׁקָלִ֑ים וְלַנְּקֵבָ֖ה ע [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter27 {
            get {
                return ResourceManager.GetString("Chapter27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וְאִם־זֶ֥בַח שְׁלָמִ֖ים קָרְבָּנ֑וֹ אִ֤ם מִן־הַבָּקָר֙ ה֣וּא מַקְרִ֔יב אִם־זָכָר֙ אִם־נְקֵבָ֔ה תָּמִ֥ים יַקְרִיבֶ֖נּוּ לִפְנֵ֥י יְהוָֽה׃&amp;וְסָמַ֤ךְ יָדוֹ֙ עַל־רֹ֣אשׁ קָרְבָּנ֔וֹ וּשְׁחָט֕וֹ פֶּ֖תַח אֹ֣הֶל מוֹעֵ֑ד וְזָֽרְק֡וּ בְּנֵי֩ אַֽהֲרֹ֨ן הַכֹּֽהֲנִ֧ים אֶת־הַדָּ֛ם עַל־הַמִּזְבֵּ֖חַ סָבִֽיב׃&amp;וְהִקְרִיב֙ מִזֶּ֣בַח הַשְּׁלָמִ֔ים אִשֶּׁ֖ה לַֽיהוָ֑ה אֶת־הַחֵ֨לֶב֙ הַֽמְכַסֶּ֣ה אֶת־הַקֶּ֔רֶב וְאֵת֙ כָּל־הַחֵ֔לֶב אֲשֶׁ֖ר עַל־הַקֶּֽרֶב׃&amp;וְאֵת֙ שְׁתֵּ֣י הַכְּלָיֹ֔ת וְאֶת־הַחֵ֨לֶב֙ אֲשֶׁ֣ר עֲלֵהֶ֔ן אֲשֶׁ֖ר עַל־הַכְ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter3 {
            get {
                return ResourceManager.GetString("Chapter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֥ר יְהוָ֖ה אֶל־מֹשֶׁ֥ה לֵּאמֹֽר׃&amp;דַּבֵּ֞ר אֶל־בְּנֵ֣י יִשְׂרָאֵל֮ לֵאמֹר֒ נֶ֗פֶשׁ כִּֽי־תֶחֱטָ֤א בִשְׁגָגָה֙ מִכֹּל֙ מִצְו֣‍ֹת יְהוָ֔ה אֲשֶׁ֖ר לֹ֣א תֵֽעָשֶׂ֑ינָה וְעָשָׂ֕ה מֵֽאַחַ֖ת מֵהֵֽנָּה׃&amp;אִ֣ם הַכֹּהֵ֧ן הַמָּשִׁ֛יחַ יֶֽחֱטָ֖א לְאַשְׁמַ֣ת הָעָ֑ם וְהִקְרִ֡יב עַ֣ל חַטָּאתוֹ֩ אֲשֶׁ֨ר חָטָ֜א פַּ֣ר בֶּן־בָּקָ֥ר תָּמִ֛ים לַֽיהוָ֖ה לְחַטָּֽאת׃&amp;וְהֵבִ֣יא אֶת־הַפָּ֗ר אֶל־פֶּ֛תַח אֹ֥הֶל מוֹעֵ֖ד לִפְנֵ֣י יְהוָ֑ה וְסָמַ֤ךְ אֶת־יָדוֹ֙ עַל־רֹ֣אשׁ הַפָּ֔ר וְשָׁחַ֥ט אֶת־הַפָּ֖ר לִפְנֵ֥י יְהוָֽה׃&amp;וְלָקַ֛ח הַכֹּ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter4 {
            get {
                return ResourceManager.GetString("Chapter4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וְנֶ֣פֶשׁ כִּֽי־תֶחֱטָ֗א וְשָֽׁמְעָה֙ ק֣וֹל אָלָ֔ה וְה֣וּא עֵ֔ד א֥וֹ רָאָ֖ה א֣וֹ יָדָ֑ע אִם־ל֥וֹא יַגִּ֖יד וְנָשָׂ֥א עֲו‍ֹנֽוֹ׃&amp;א֣וֹ נֶ֗פֶשׁ אֲשֶׁ֣ר תִּגַּע֮ בְּכָל־דָּבָ֣ר טָמֵא֒ אוֹ֩ בְנִבְלַ֨ת חַיָּ֜ה טְמֵאָ֗ה א֚וֹ בְּנִבְלַת֙ בְּהֵמָ֣ה טְמֵאָ֔ה א֕וֹ בְּנִבְלַ֖ת שֶׁ֣רֶץ טָמֵ֑א וְנֶעְלַ֣ם מִמֶּ֔נּוּ וְה֥וּא טָמֵ֖א וְאָשֵֽׁם׃&amp;א֣וֹ כִ֤י יִגַּע֙ בְּטֻמְאַ֣ת אָדָ֔ם לְכֹל֙ טֻמְאָת֔וֹ אֲשֶׁ֥ר יִטְמָ֖א בָּ֑הּ וְנֶעְלַ֣ם מִמֶּ֔נּוּ וְה֥וּא יָדַ֖ע וְאָשֵֽׁם׃&amp;א֣וֹ נֶ֡פֶשׁ כִּ֣י תִשָּׁבַע֩ לְבַטֵּ֨א בִשְׂפָתַ֜יִם לְ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter5 {
            get {
                return ResourceManager.GetString("Chapter5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֥ר יְהוָ֖ה אֶל־מֹשֶׁ֥ה לֵּאמֹֽר׃&amp;צַ֤ו אֶֽת־אַהֲרֹן֙ וְאֶת־בָּנָ֣יו לֵאמֹ֔ר זֹ֥את תּוֹרַ֖ת הָֽעֹלָ֑ה הִ֣וא הָֽעֹלָ֡ה עַל֩ מֽוֹקְדָ֨ה עַל־הַמִּזְבֵּ֤חַ כָּל־הַלַּ֨יְלָה֙ עַד־הַבֹּ֔קֶר וְאֵ֥שׁ הַמִּזְבֵּ֖חַ תּ֥וּקַד בּֽוֹ׃&amp;וְלָבַ֨שׁ הַכֹּהֵ֜ן מִדּ֣וֹ בַ֗ד וּמִֽכְנְסֵי־בַד֮ יִלְבַּ֣שׁ עַל־בְּשָׂרוֹ֒ וְהֵרִ֣ים אֶת־הַדֶּ֗שֶׁן אֲשֶׁ֨ר תֹּאכַ֥ל הָאֵ֛שׁ אֶת־הָֽעֹלָ֖ה עַל־הַמִּזְבֵּ֑חַ וְשָׂמ֕וֹ אֵ֖צֶל הַמִּזְבֵּֽחַ׃&amp;וּפָשַׁט֙ אֶת־בְּגָדָ֔יו וְלָבַ֖שׁ בְּגָדִ֣ים אֲחֵרִ֑ים וְהוֹצִ֤יא אֶת־הַדֶּ֨שֶׁן֙ אֶל־מִח֣ו [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter6 {
            get {
                return ResourceManager.GetString("Chapter6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וְזֹ֥את תּוֹרַ֖ת הָֽאָשָׁ֑ם קֹ֥דֶשׁ קָֽדָשִׁ֖ים הֽוּא׃&amp;בִּמְק֗וֹם אֲשֶׁ֤ר יִשְׁחֲטוּ֙ אֶת־הָ֣עֹלָ֔ה יִשְׁחֲט֖וּ אֶת־הָֽאָשָׁ֑ם וְאֶת־דָּמ֛וֹ יִזְרֹ֥ק עַל־הַמִּזְבֵּ֖חַ סָבִֽיב׃&amp;וְאֵ֥ת כָּל־חֶלְבּ֖וֹ יַקְרִ֣יב מִמֶּ֑נּוּ אֵ֚ת הָֽאַלְיָ֔ה וְאֶת־הַחֵ֖לֶב הַֽמְכַסֶּ֥ה אֶת־הַקֶּֽרֶב׃&amp;וְאֵת֙ שְׁתֵּ֣י הַכְּלָיֹ֔ת וְאֶת־הַחֵ֨לֶב֙ אֲשֶׁ֣ר עֲלֵיהֶ֔ן אֲשֶׁ֖ר עַל־הַכְּסָלִ֑ים וְאֶת־הַיֹּתֶ֨רֶת֙ עַל־הַכָּבֵ֔ד עַל־הַכְּלָיֹ֖ת יְסִירֶֽנָּה׃&amp;וְהִקְטִ֨יר אֹתָ֤ם הַכֹּהֵן֙ הַמִּזְבֵּ֔חָה אִשֶּׁ֖ה לַֽיהוָ֑ה אָשָׁ֖ם הֽוּא׃&amp;כָּל [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter7 {
            get {
                return ResourceManager.GetString("Chapter7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַיְדַבֵּ֥ר יְהוָ֖ה אֶל־מֹשֶׁ֥ה לֵּאמֹֽר׃&amp;קַ֤ח אֶֽת־אַהֲרֹן֙ וְאֶת־בָּנָ֣יו אִתּ֔וֹ וְאֵת֙ הַבְּגָדִ֔ים וְאֵ֖ת שֶׁ֣מֶן הַמִּשְׁחָ֑ה וְאֵ֣ת ׀ פַּ֣ר הַֽחַטָּ֗את וְאֵת֙ שְׁנֵ֣י הָֽאֵילִ֔ים וְאֵ֖ת סַ֥ל הַמַּצּֽוֹת׃&amp;וְאֵ֥ת כָּל־הָֽעֵדָ֖ה הַקְהֵ֑ל אֶל־פֶּ֖תַח אֹ֥הֶל מוֹעֵֽד׃&amp;וַיַּ֣עַשׂ מֹשֶׁ֔ה כַּֽאֲשֶׁ֛ר צִוָּ֥ה יְהוָ֖ה אֹת֑וֹ וַתִּקָּהֵל֙ הָֽעֵדָ֔ה אֶל־פֶּ֖תַח אֹ֥הֶל מוֹעֵֽד׃&amp;וַיֹּ֥אמֶר מֹשֶׁ֖ה אֶל־הָֽעֵדָ֑ה זֶ֣ה הַדָּבָ֔ר אֲשֶׁר־צִוָּ֥ה יְהוָ֖ה לַֽעֲשֽׂוֹת׃&amp;וַיַּקְרֵ֣ב מֹשֶׁ֔ה אֶֽת־אַהֲרֹ֖ן וְאֶת־בָּנָ֑יו וַיִ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter8 {
            get {
                return ResourceManager.GetString("Chapter8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וַֽיְהִי֙ בַּיּ֣וֹם הַשְּׁמִינִ֔י קָרָ֣א מֹשֶׁ֔ה לְאַֽהֲרֹ֖ן וּלְבָנָ֑יו וּלְזִקְנֵ֖י יִשְׂרָאֵֽל׃&amp;וַיֹּ֣אמֶר אֶֽל־אַהֲרֹ֗ן קַח־לְ֠ךָ עֵ֣גֶל בֶּן־בָּקָ֧ר לְחַטָּ֛את וְאַ֥יִל לְעֹלָ֖ה תְּמִימִ֑ם וְהַקְרֵ֖ב לִפְנֵ֥י יְהוָֽה׃&amp;וְאֶל־בְּנֵ֥י יִשְׂרָאֵ֖ל תְּדַבֵּ֣ר לֵאמֹ֑ר קְח֤וּ שְׂעִיר־עִזִּים֙ לְחַטָּ֔את וְעֵ֨גֶל וָכֶ֧בֶשׂ בְּנֵֽי־שָׁנָ֛ה תְּמִימִ֖ם לְעֹלָֽה׃&amp;וְשׁ֨וֹר וָאַ֜יִל לִשְׁלָמִ֗ים לִזְבֹּ֨חַ֙ לִפְנֵ֣י יְהוָ֔ה וּמִנְחָ֖ה בְּלוּלָ֣ה בַשָּׁ֑מֶן כִּ֣י הַיּ֔וֹם יְהוָ֖ה נִרְאָ֥ה אֲלֵיכֶֽם׃&amp;וַיִּקְח֗וּ אֵ֚ת  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter9 {
            get {
                return ResourceManager.GetString("Chapter9", resourceCulture);
            }
        }
    }
}
