//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yahadut.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yahadut.Resources.LocalResources", typeof(LocalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אמה (חזון אי&quot;ש).
        /// </summary>
        public static string LengthAmmahC {
            get {
                return ResourceManager.GetString("LengthAmmahC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אמה (גר&quot;ח נאה).
        /// </summary>
        public static string LengthAmmahG {
            get {
                return ResourceManager.GetString("LengthAmmahG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אמה (רמב&quot;ם).
        /// </summary>
        public static string LengthAmmahR {
            get {
                return ResourceManager.GetString("LengthAmmahR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סנטימטר.
        /// </summary>
        public static string LengthCm {
            get {
                return ResourceManager.GetString("LengthCm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אצבע (חזון אי&quot;ש).
        /// </summary>
        public static string LengthFingerC {
            get {
                return ResourceManager.GetString("LengthFingerC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אצבע (גר&quot;ח נאה).
        /// </summary>
        public static string LengthFingerG {
            get {
                return ResourceManager.GetString("LengthFingerG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אצבע (רמב&quot;ם).
        /// </summary>
        public static string LengthFingerR {
            get {
                return ResourceManager.GetString("LengthFingerR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קילומטר.
        /// </summary>
        public static string LengthKm {
            get {
                return ResourceManager.GetString("LengthKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מטר.
        /// </summary>
        public static string LengthMeter {
            get {
                return ResourceManager.GetString("LengthMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מיל (חזון אי&quot;ש).
        /// </summary>
        public static string LengthMilC {
            get {
                return ResourceManager.GetString("LengthMilC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מיל (גר&quot;ח נאה).
        /// </summary>
        public static string LengthMilG {
            get {
                return ResourceManager.GetString("LengthMilG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מיל (רמב&quot;ם).
        /// </summary>
        public static string LengthMilR {
            get {
                return ResourceManager.GetString("LengthMilR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסה (חזון אי&quot;ש).
        /// </summary>
        public static string LengthParsahC {
            get {
                return ResourceManager.GetString("LengthParsahC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסה (גר&quot;ח נאה).
        /// </summary>
        public static string LengthParsahG {
            get {
                return ResourceManager.GetString("LengthParsahG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסה (רמב&quot;ם).
        /// </summary>
        public static string LengthParsahR {
            get {
                return ResourceManager.GetString("LengthParsahR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ריס (חזון אי&quot;ש).
        /// </summary>
        public static string LengthRisC {
            get {
                return ResourceManager.GetString("LengthRisC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ריס (גר&quot;ח נאה).
        /// </summary>
        public static string LengthRisG {
            get {
                return ResourceManager.GetString("LengthRisG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ריס (רמב&quot;ם).
        /// </summary>
        public static string LengthRisR {
            get {
                return ResourceManager.GetString("LengthRisR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיט (חזון אי&quot;ש).
        /// </summary>
        public static string LengthSitC {
            get {
                return ResourceManager.GetString("LengthSitC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיט (גר&quot;ח נאה).
        /// </summary>
        public static string LengthSitG {
            get {
                return ResourceManager.GetString("LengthSitG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיט (רמב&quot;ם).
        /// </summary>
        public static string LengthSitR {
            get {
                return ResourceManager.GetString("LengthSitR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טפח (חזון אי&quot;ש).
        /// </summary>
        public static string LengthTefachC {
            get {
                return ResourceManager.GetString("LengthTefachC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טפח (גר&quot;ח נאה).
        /// </summary>
        public static string LengthTefachG {
            get {
                return ResourceManager.GetString("LengthTefachG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טפח (רמב&quot;ם).
        /// </summary>
        public static string LengthTefachR {
            get {
                return ResourceManager.GetString("LengthTefachR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זרת (חזון אי&quot;ש).
        /// </summary>
        public static string LengthZerretC {
            get {
                return ResourceManager.GetString("LengthZerretC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זרת (גר&quot;ח נאה).
        /// </summary>
        public static string LengthZerretG {
            get {
                return ResourceManager.GetString("LengthZerretG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זרת (רמב&quot;ם).
        /// </summary>
        public static string LengthZerretR {
            get {
                return ResourceManager.GetString("LengthZerretR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביצה (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeBeitzaC {
            get {
                return ResourceManager.GetString("VolumeBeitzaC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביצה (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeBeitzaG {
            get {
                return ResourceManager.GetString("VolumeBeitzaG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביצה (רמב&quot;ם).
        /// </summary>
        public static string VolumeBeitzaR {
            get {
                return ResourceManager.GetString("VolumeBeitzaR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איפה (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeEifaC {
            get {
                return ResourceManager.GetString("VolumeEifaC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איפה (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeEifaG {
            get {
                return ResourceManager.GetString("VolumeEifaG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איפה (רמב&quot;ם).
        /// </summary>
        public static string VolumeEifaR {
            get {
                return ResourceManager.GetString("VolumeEifaR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גרוגרת (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeGrogeretC {
            get {
                return ResourceManager.GetString("VolumeGrogeretC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גרוגרת (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeGrogeretG {
            get {
                return ResourceManager.GetString("VolumeGrogeretG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גרוגרת (רמב&quot;ם).
        /// </summary>
        public static string VolumeGrogeretR {
            get {
                return ResourceManager.GetString("VolumeGrogeretR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הין (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeHinC {
            get {
                return ResourceManager.GetString("VolumeHinC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הין (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeHinG {
            get {
                return ResourceManager.GetString("VolumeHinG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הין (רמב&quot;ם).
        /// </summary>
        public static string VolumeHinR {
            get {
                return ResourceManager.GetString("VolumeHinR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קב (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeKavC {
            get {
                return ResourceManager.GetString("VolumeKavC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קב (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeKavG {
            get {
                return ResourceManager.GetString("VolumeKavG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קב (רמב&quot;ם).
        /// </summary>
        public static string VolumeKavR {
            get {
                return ResourceManager.GetString("VolumeKavR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כור (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeKorC {
            get {
                return ResourceManager.GetString("VolumeKorC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כור (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeKorG {
            get {
                return ResourceManager.GetString("VolumeKorG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כור (רמב&quot;ם).
        /// </summary>
        public static string VolumeKorR {
            get {
                return ResourceManager.GetString("VolumeKorR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קורטוב (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeKortovC {
            get {
                return ResourceManager.GetString("VolumeKortovC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קורטוב (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeKortovG {
            get {
                return ResourceManager.GetString("VolumeKortovG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קורטוב (רמב&quot;ם).
        /// </summary>
        public static string VolumeKortovR {
            get {
                return ResourceManager.GetString("VolumeKortovR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לתך (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeLettechC {
            get {
                return ResourceManager.GetString("VolumeLettechC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לתך (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeLettechG {
            get {
                return ResourceManager.GetString("VolumeLettechG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לתך (רמב&quot;ם).
        /// </summary>
        public static string VolumeLettechR {
            get {
                return ResourceManager.GetString("VolumeLettechR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ליטרא (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeLitraC {
            get {
                return ResourceManager.GetString("VolumeLitraC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ליטרא (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeLitraG {
            get {
                return ResourceManager.GetString("VolumeLitraG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ליטר.
        /// </summary>
        public static string VolumeLitter {
            get {
                return ResourceManager.GetString("VolumeLitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לוג (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeLogC {
            get {
                return ResourceManager.GetString("VolumeLogC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לוג (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeLogG {
            get {
                return ResourceManager.GetString("VolumeLogG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לוג (רמב&quot;ם).
        /// </summary>
        public static string VolumeLogR {
            get {
                return ResourceManager.GetString("VolumeLogR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מיליליטר.
        /// </summary>
        public static string VolumeMl {
            get {
                return ResourceManager.GetString("VolumeMl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עומר (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeOmerC {
            get {
                return ResourceManager.GetString("VolumeOmerC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עומר (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeOmerG {
            get {
                return ResourceManager.GetString("VolumeOmerG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עומר (רמב&quot;ם).
        /// </summary>
        public static string VolumeOmerR {
            get {
                return ResourceManager.GetString("VolumeOmerR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רביעית (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeReviitC {
            get {
                return ResourceManager.GetString("VolumeReviitC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רביעית (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeReviitG {
            get {
                return ResourceManager.GetString("VolumeReviitG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רביעית (רמב&quot;ם).
        /// </summary>
        public static string VolumeReviitR {
            get {
                return ResourceManager.GetString("VolumeReviitR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רובע (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeRovaC {
            get {
                return ResourceManager.GetString("VolumeRovaC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רובע (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeRovaG {
            get {
                return ResourceManager.GetString("VolumeRovaG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רובע (רמב&quot;ם).
        /// </summary>
        public static string VolumeRovaR {
            get {
                return ResourceManager.GetString("VolumeRovaR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סאה (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeSeaaC {
            get {
                return ResourceManager.GetString("VolumeSeaaC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סאה (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeSeaaG {
            get {
                return ResourceManager.GetString("VolumeSeaaG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סאה (רמב&quot;ם).
        /// </summary>
        public static string VolumeSeaaR {
            get {
                return ResourceManager.GetString("VolumeSeaaR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמינית (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeShminitC {
            get {
                return ResourceManager.GetString("VolumeShminitC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמינית (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeShminitG {
            get {
                return ResourceManager.GetString("VolumeShminitG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עוכלה (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeUkalahC {
            get {
                return ResourceManager.GetString("VolumeUkalahC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עוכלה (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeUkalahG {
            get {
                return ResourceManager.GetString("VolumeUkalahG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זית (חזון אי&quot;ש).
        /// </summary>
        public static string VolumeZaytC {
            get {
                return ResourceManager.GetString("VolumeZaytC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זית (גר&quot;ח נאה).
        /// </summary>
        public static string VolumeZaytG {
            get {
                return ResourceManager.GetString("VolumeZaytG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זית (רמב&quot;ם).
        /// </summary>
        public static string VolumeZaytR {
            get {
                return ResourceManager.GetString("VolumeZaytR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דרכון.
        /// </summary>
        public static string WeightDarkon {
            get {
                return ResourceManager.GetString("WeightDarkon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דינר.
        /// </summary>
        public static string WeightDinar {
            get {
                return ResourceManager.GetString("WeightDinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גרם.
        /// </summary>
        public static string WeightGram {
            get {
                return ResourceManager.GetString("WeightGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איסר.
        /// </summary>
        public static string WeightIssar {
            get {
                return ResourceManager.GetString("WeightIssar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קילוגרם.
        /// </summary>
        public static string WeightKilogram {
            get {
                return ResourceManager.GetString("WeightKilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מעה.
        /// </summary>
        public static string WeightMaah {
            get {
                return ResourceManager.GetString("WeightMaah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנה.
        /// </summary>
        public static string WeightManeh {
            get {
                return ResourceManager.GetString("WeightManeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פונדיון.
        /// </summary>
        public static string WeightPondion {
            get {
                return ResourceManager.GetString("WeightPondion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרוטה.
        /// </summary>
        public static string WeightPrutah {
            get {
                return ResourceManager.GetString("WeightPrutah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סלע.
        /// </summary>
        public static string WeightSela {
            get {
                return ResourceManager.GetString("WeightSela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שעורים.
        /// </summary>
        public static string WeightSeorim {
            get {
                return ResourceManager.GetString("WeightSeorim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שקל.
        /// </summary>
        public static string WeightShekel {
            get {
                return ResourceManager.GetString("WeightShekel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טרעפיק.
        /// </summary>
        public static string WeightTarafik {
            get {
                return ResourceManager.GetString("WeightTarafik", resourceCulture);
            }
        }
    }
}
