//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrayPal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrayersAshkenaz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrayersAshkenaz() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrayPal.Resources.PrayersAshkenaz", typeof(PrayersAshkenaz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הָרַחֲמָן הוּא יַחֲזִיר לָנוּ עֲבוֹדַת בֵּית הַמִּקְדָּשׁ לִמְקוֹמָהּ, בִּמְהֵרָה בְיָמֵינוּ אָמֵן סֶלָה.
        ///יְהִי רָצוֹן מִלְּפָנֶיךָ יְיָ אֱלֹהֵינוּ וֵאלֹהֵי אֲבוֹתֵינוּ, שֶׁיִּבָּנֶה בֵּית הַמִּקְדָּשׁ בִּמְהֵרָה בְּיָמֵינוּ וְתֵן חֶלְקֵנוּ בְּתוֹרָתֶךָ. וְשָׁם נַעֲבָדְךָ בְּיִרְאָה כִּימֵי עוֹלָם וּכְשָׁנִים קַדְמוֹנִיּוֹת..
        /// </summary>
        public static string AfterSfiratHaOmer1 {
            get {
                return ResourceManager.GetString("AfterSfiratHaOmer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רִבּוֹנוֹ שֶׁל עוֹלָם, אַתָּה צִוִּיתָנִי עַל יְדֵי מֹשֶׁה עַבְדֶּךָ לִסְפֹּר סְפִירַת הָעֹמֶר כְּדֵי לְטַהֲרֵנוּ מִקְּלִפּוֹתֵינוּ וּמִטֻּמְאוֹתֵינוּ, כְּמוֹ שֶּׁכָּתַבְתָּ בְּתוֹרָתֶךָ: וּסְפַרְתֶּם לָכֶם מִמָּחֳרָת הַשַּׁבָּת מִיּוֹם הֲבִיאֲכֶם אֶת עֹמֶר הַתְּנוּפָה שֶׁבַע שַׁבָּתוֹת תְּמִימוֹת תִּהְיֶינָה. עַד מִמָּחֳרָת הַשַּׁבָּת הַשְּׁבִיעִית תִּסְפְּרוּ חֲמִשִּׁים יוֹם, כְּדֵי שֶׁיִּטָּהֲרוּ נַפְשׁוֹת עַמְּךָ יִשְׂרָאֵל מִזֻּהֲמָתָם. וּבְכֵן יְהִי רָצוֹן מִלְּפָנֶיךָ יְיָ אֱלֹהֵינוּ וֵאלֹהֵי אֲבוֹתֵ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AfterSfiratHaOmer2_F0 {
            get {
                return ResourceManager.GetString("AfterSfiratHaOmer2_F0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עָלֵינוּ לְשַׁבֵּחַ לַאֲדוֹן הַכֹּל, לָתֵת גְּדֻלָּה לְיוֹצֵר בְּרֵאשִׁית, שֶׁלֹּא עָשָׂנוּ כְּגוֹיֵי הָאֲרָצוֹת, וְלֹא שָׂמָנוּ כְּמִשְׁפְּחוֹת הָאֲדָמָה, שֶׁלֹּא שָׂם חֶלְקֵנוּ כָּהֶם וְגוֹרָלֵנוּ כְּכָל הֲמוֹנָם. שֶׁהֵם מִשְׁתַּחֲוִים לְהֶבֶל וָרִיק וּמִתְפַּלְּלִים אֶל אֵל לֹא יוֹשִׁיעַ. וַאֲנַחְנוּ כּוֹרְעִים וּמִשְׁתַּחֲוִים וּמוֹדִים לִפְנֵי מֶלֶךְ מַלְכֵי הַמְּלָכִים הַקָּדוֹשׁ בָּרוּךְ הוּא, שֶׁהוּא נוֹטֶה שָׁמַיִם וְיֹסֵד אָרֶץ, וּמוֹשַׁב יְקָרוֹ בַּשָּׁמַיִם מִמַּעַל, וּשְׁכִינַת עֻזּוֹ בְּגָבְהֵ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AleinuLeshabeach {
            get {
                return ResourceManager.GetString("AleinuLeshabeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, אֲשֶׁר יָצַר אֶת הָאָדָם בְּחָכְמָה, וּבָרָא בוֹ נְקָבִים נְקָבִים חֲלוּלִים חֲלוּלִים. גָּלוּי וְיָדוּעַ לִפְנֵי כִסֵּא כְבוֹדֶךָ, שֶׁאִם יִפָּתֵחַ אֶחָד מֵהֶם אוֹ יִסָּתֵם אֶחָד מֵהֶם, אִי אֶפְשַׁר לְהִתְקַיֵּם וְלַעֲמוֹד לְפָנֶיךָ. בָּרוּךְ אַתָּה יְיָ, רוֹפֵא כָל בָּשָׂר וּמַפְלִיא לַעֲשׂוֹת..
        /// </summary>
        public static string AsherYatzar {
            get {
                return ResourceManager.GetString("AsherYatzar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הֲרֵינִי מְזַמֵּן אֶת פִּי לְהוֹדוֹת וּלְהַלֵּל וּלְשַׁבֵּחַ אֶת בּוֹרְאִי, לְשֵׁם יִחוּד קוּדְשָׁא בְּרִיךְ הוּא וּשְׁכִינְתֵּיהּ עַל יְדֵי הַהוּא טָמִיר וְנֶעְלָם בְּשֵׁם כָּל יִשְׂרָאֵל.
        ///בָּרוּךְ שֶׁאָמַר וְהָיָה הָעוֹלָם, בָּרוּךְ הוּא, בָּרוּךְ עֹשֶׂה בְרֵאשִׁית, בָּרוּךְ אוֹמֵר וְעֹשֶׂה, בָּרוּךְ גּוֹזֵר וּמְקַיֵּם, בָּרוּךְ מְרַחֵם עַל הָאָרֶץ, בָּרוּךְ מְרַחֵם עַל הַבְּרִיּוֹת, בָּרוּךְ מְשַׁלֵּם שָׂכָר טוֹב לִירֵאָיו, בָּרוּךְ חַי לָעַד וְקַיָּם לָנֶצַח, בָּרוּךְ פּוֹדֶה וּמַצִּיל, בָּרוּךְ שְׁמוֹ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BaruchSheamar {
            get {
                return ResourceManager.GetString("BaruchSheamar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, הַמַּפִּיל חֶבְלֵי שֵׁנָה עַל עֵינָי וּתְנוּמָה עַל עַפְעַפָּי. וִיהִי רָצוֹן מִלְפָנֶיךָ יְיָ אֱלֹהַי וֵאלֹהֵי אֲבוֹתַי, שֶׁתַּשְׁכִּיבֵנִי לְשָׁלוֹם וְתַעֲמִידֵנִי לְשָׁלוֹם, וְאַל יְבַהֲלוּנִי רַעֲיוֹנַי וַחֲלוֹמוֹת רָעִים וְהִרְהוּרִים רָעִים, וּתְהִי מִטָּתִי שְׁלֵמָה לְפָנֶיךָ, וְהָאֵר עֵינַי פֶּן אִישַׁן הַמָּוֶת, כִּי אַתָּה הַמֵּאִיר לְאִישׁוֹן בַּת עַיִן. בָּרוּךְ אַתָּה יְיָ, הַמֵּאִיר לָעוֹלָם כֻּלוֹ בִּכְבוֹדוֹ..
        /// </summary>
        public static string BedtimeShma10 {
            get {
                return ResourceManager.GetString("BedtimeShma10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, פּוֹקֵחַ עִוְרִים.
        ///בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, מַלְבִּישׁ עֲרֻמִּים.
        ///בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, מַתִּיר אֲסוּרִים.
        ///בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, זוֹקֵף כְּפוּפִים.
        ///בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, רוֹקַע הָאָרֶץ עַל הַמָּיִם.
        ///בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, שֶׁעָשָׂה לִּי כָּל צָרְכִּי.
        ///בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, הַמֵּכִין מִצְעֲדֵי גָבֶר [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BirkotHashachar2 {
            get {
                return ResourceManager.GetString("BirkotHashachar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וִיהִי רָצוֹן מִלְּפָנֶיךָ יְיָ אֱלֹהֵינוּ וֵאלֹהֵי אֲבוֹתֵינוּ, שֶׁתַּרְגִּילֵנִי בְּתוֹרָתֶךָ, וְדַבְּקֵנִי בְּמִצְוֹתֶיךָ, וְאַל תְּבִיאֵנִי לֹא לִידֵי חֵטְא. וְלֹא לִידֵי עֲבֵרָה וְעָוֹן, וְלֹא לִידֵי נִסָּיוֹן וְלֹא לִידֵי בִזָּיוֹן, וְאַל־יִשְׁלֹט בִּי יֵצֶר הָרָע, וְרַחֲקֵנִי מֵאָדָם רָע וּמֵחָבֵר רָע, וְדַבְּקֵנִי בְּיֵצֶר הַטוֹב וּבְמַעֲשִׂים טוֹבִים, וְכֹף אֶת יִצְרִי לְהִשְׁתַּעְבֶּד־לָךְ, וּתְנֵנִי הַיּוֹם וּבְכָל יוֹם לְחֵן וּלְחֶסֶד וּלְרַחֲמִים בְּעֵינֶיךָ וּבְעֵינֵי כָל רוֹאַי, וְתִגְמְלֵנִי [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BirkotHashachar3 {
            get {
                return ResourceManager.GetString("BirkotHashachar3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יְהִי רָצוֹן מִלְּפָנֶיךָ יְיָ אֱלֹהַי וֵאלֹהֵי אֲבוֹתַי, שֶׁתַּצִּילֵנִי הַיּוֹם וּבְכָל־יוֹם מֵעַזֵּי פָנִים וּמֵעַזּוּת פָּנִים, מֵאָדָם רָע וּמֵחָבֵר רָע, וּמִשָּׁכֵן רָע, וּמִפֶּגַע רָע וּמִשָּׂטָן הַמַּשְׁחִית, מִדִּין קָשֶׁה, וּמִבַּעַל דִּין קָשֶׁה, בֵּין שֶׁהוּא בֶן בְּרִית וּבֵין שֶׁאֵינוֹ בֶן בְּרִית..
        /// </summary>
        public static string BirkotHashachar4 {
            get {
                return ResourceManager.GetString("BirkotHashachar4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, אֲשֶׁר קִדְּשָׁנוּ בְּמִצְוֹתָיו וְצִוָּנוּ לַעֲסֹק בְּדִבְרֵי תוֹרָה.
        ///
        ///וְהַעֲרֶב־נָא יְיָ אֱלֹהֵינוּ אֶת דִּבְרֵי תוֹרָתְךָ בְּפִינוּ וּבְפִיוֹת עַמְּךָ בֵּית יִשְׂרָאֵל, וְנִהְיֶה אֲנַחְנוּ וְצֶאֱצָאֵינוּ וְצֶאֱצָאֵי עַמְּךָ בֵּית יִשְׂרָאֵל כֻּלָּנוּ יוֹדְעֵי שְׁמֶךָ וְלוֹמְדֵי תוֹרָתֶךָ. בָּרוּךְ אַתָּה יְיָ, הַמְּלַמֵּד תּוֹרָה לְעַמּוֹ יִשְׂרָאֵל.
        ///
        ///בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, אֲשֶׁר בָּחַר בָּנוּ מִכָּל הָעַמִּים וְנָתַן לָנוּ א [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BirkotHatorah {
            get {
                return ResourceManager.GetString("BirkotHatorah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אֱמֶת וֶאֱמוּנָה כָּל זֹאת וְקַיָּם עָלֵינוּ, כִּי הוּא יְיָ אֱלֹהֵינוּ וְאֵין זוּלָתוֹ. וַאֲנַחְנוּ יִשְׂרָאֵל עַמּוֹ. הַפּוֹדֵנוּ מִיַּד מְלָכִים, מַלְכֵּנוּ הַגּוֹאֲלֵנוּ מִכַּף כָּל הֶעָרִיצִים, הָאֵל הַנִּפְרָע לָנוּ מִצָּרֵינוּ, וְהַמְשַׁלֵּם גְּמוּל לְכָל אוֹיְבֵי נַפְשֵׁנוּ. הָעוֹשֶׂה גְדוֹלוֹת עַד אֵין חֵקֶר וְנִפְלָאוֹת עַד אֵין מִסְפָּר. הַשָּׂם נַפְשֵׁנוּ בַּחַיִּים, וְלֹא נָתַן לַמּוֹט רַגְלֵנוּ. הַמַּדְרִיכֵנוּ עַל בָּמוֹת אוֹיְבֵינוּ, וַיָּרֶם קַרְנֵנוּ עַל כָּל שׂוֹנְאֵינוּ. הָעוֹשֶׂה לָנוּ  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrachotAfterShmaArvit1 {
            get {
                return ResourceManager.GetString("BrachotAfterShmaArvit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הַשְׁכִּיבֵנוּ יְיָ אֱלֹהֵינוּ לְשָׁלוֹם, וְהַעֲמִידֵנוּ מַלְכֵּנוּ לְחַיִּים, וּפְרוֹשׂ עָלֵינוּ סֻכַּת שְׁלוֹמֶךָ, וְתַקְּנֵנוּ בְּעֵצָה טוֹבָה מִלְּפָנֶיךָ, וְהוֹשִׁיעֵנוּ לְמַעַן שְׁמֶךָ. וְהָגֵן בַּעֲדֵנוּ, וְהָסֵר מֵעָלֵינוּ אוֹיֵב דֶּבֶר וְחֶרֶב וְרָעָב וְיָגוֹן, וְהָסֵר שָׂטָן מִלְּפָנֵינוּ וּמֵאַחֲרֵינוּ, וּבְצֵל כְּנָפֶיךָ תַּסְתִּירֵנוּ. כִּי אֵל שׁוֹמְרֵנוּ וּמַצִּילֵנוּ אָתָּה, כִּי אֵל מֶלֶךְ חַנּוּן וְרַחוּם אָתָּה. וּשְׁמוֹר צֵאתֵנוּ וּבוֹאֵנוּ לְחַיִּים וּלְשָׁלוֹם מֵעַתָּה וְעַד עוֹלָם. בּ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrachotAfterShmaArvit2 {
            get {
                return ResourceManager.GetString("BrachotAfterShmaArvit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אֱמֶת, וְיַצִּיב, וְנָכוֹן, וְקַיָּם, וְיָשָׁר, וְנֶאֱמָן, וְאָהוּב וְחָבִיב, וְנֶחְמָד וְנָעִים, וְנוֹרָא וְאַדִּיר, וּמְתֻקָּן וּמְקֻבָּל, וְטוֹב וְיָפֶה, הַדָּבָר הַזֶּה עָלֵינוּ לְעוֹלָם וָעֶד. אֱמֶת, אֱלֹהֵי עוֹלָם מַלְכֵּנוּ, צוּר יַעֲקֹב מָגֵן יִשְׁעֵנוּ, לְדֹר וָדֹר הוּא קַיָּם וּשְׁמוֹ קַיָּם, וְכִסְאוֹ נָכוֹן, וּמַלְכוּתוֹ וֶאֱמוּנָתוֹ לָעַד קַיֶּמֶת. וּדְבָרָיו חָיִים וְקַיָּמִים, נֶאֱמָנִים וְנֶחֱמָדִים לָעַד וּלְעוֹלְמֵי עוֹלָמִים, עַל אֲבוֹתֵינוּ וְעָלֵינוּ, עַל בָּנֵינוּ וְעַל דּוֹרוֹתֵינוּ,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrachotAfterShmaShacharit1 {
            get {
                return ResourceManager.GetString("BrachotAfterShmaShacharit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עֶזְרַת אֲבוֹתֵינוּ אַתָּה הוּא מֵעוֹלָם, מָגֵן וּמוֹשִׁיעַ לִבְנֵיהֶם אַחֲרֵיהֶם בְּכָל דּוֹר וָדוֹר. בְּרוּם עוֹלָם מוֹשָׁבֶךָ, וּמִשְׁפָּטֶיךָ וְצִדְקָתְךָ עַד אַפְסֵי אָרֶץ. אַשְׁרֵי אִישׁ שֶׁיִּשְׁמַע לְמִצְוֹתֶיךָ וְתוֹרָתְךָ וּדְבָרְךָ יָשִׂים עַל לִבּוֹ. אֱמֶת, אַתָּה הוּא אָדוֹן לְעַמֶּךָ, וּמֶלֶךְ גִּבּוֹר לָרִיב רִיבָם. אֱמֶת, אַתָּה הוּא רִאשׁוֹן וְאַתָּה הוּא אַחֲרוֹן, וּמִבַּלְעָדֶיךָ אֵין לָנוּ מֶלֶךְ גּוֹאֵל וּמוֹשִׁיעַ. מִמִּצְרַיִם גְּאַלְתָּנוּ יְיָ אֱלֹהֵינוּ וּמִבֵּית עֲבָדִים פְּדִיתָנ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrachotAfterShmaShacharit2 {
            get {
                return ResourceManager.GetString("BrachotAfterShmaShacharit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שִׁירָה חֲדָשָׁה שִׁבְּחוּ גְאוּלִים לְשִׁמְךָ עַל שְׂפַת הַיָּם, יַחַד כֻּלָּם הוֹדוּ וְהִמְלִיכוּ וְאָמְרוּ:
        ///יְיָ יִמְלֹךְ לְעוֹלָם וָעֶד.
        ///
        ///צוּר יִשְׂרָאֵל, קוּמָה בְּעֶזְרַת יִשְׂרָאֵל, וּפְדֵה כִנְאֻמֶךָ יְהוּדָה וְיִשְׂרָאֵל. בָּרוּךְ אַתָּה יְיָ, גָּאַל יִשְׂרָאֵל..
        /// </summary>
        public static string BrachotAfterShmaShacharit3 {
            get {
                return ResourceManager.GetString("BrachotAfterShmaShacharit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, אֲשֶׁר בִּדְבָרוֹ מַעֲרִיב עֲרָבִים, בְּחָכְמָה פּוֹתֵחַ שְׁעָרִים, וּבִתְבוּנָה מְשַׁנֶּה עִתִּים וּמַחֲלִיף אֶת הַזְּמַנִּים, וּמְסַדֵּר אֶת הַכּוֹכָבִים בְּמִשְׁמְרוֹתֵיהֶם בָּרָקִיעַ כִּרְצוֹנוֹ. בּוֹרֵא יוֹם וָלָיְלָה, גּוֹלֵל אוֹר מִפְּנֵי חֹשֶׁךְ וְחֹשֶׁךְ מִפְּנֵי אוֹר, הַמַּעֲבִיר יוֹם וּמֵבִיא לָיְלָה, וּמַבְדִּיל בֵּין יוֹם וּבֵין לָיְלָה, יְיָ צְבָאוֹת שְׁמוֹ. אֵל חַי וְקַיָּם תָּמִיד יִמְלֹךְ עָלֵינוּ לְעוֹלָם וָעֶד, בָּרוּךְ אַתָּה יְיָ, הַמַּעֲ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrachotBeforeShmaArvit {
            get {
                return ResourceManager.GetString("BrachotBeforeShmaArvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, יוֹצֵר אוֹר וּבוֹרֵא חֹשֶׁךְ, עֹשֶׂה שָׁלוֹם וּבוֹרֵא אֶת הַכֹּל.
        ///הַמֵּאִיר לָאָרֶץ וְלַדָּרִים עָלֶיהָ בְּרַחֲמִים, וּבְטוּבוֹ מְחַדֵּשׁ בְּכָל יוֹם תָּמִיד מַעֲשֵׂה בְרֵאשִׁית. מָה רַבּוּ מַעֲשֶׂיךָ יְיָ, כֻּלָּם בְּחָכְמָה עָשִׂיתָ, מָלְאָה הָאָרֶץ קִנְיָנֶךָ. הַמֶּלֶךְ הַמְרוֹמָם לְבַדּוֹ מֵאָז, הַמְשֻׁבָּח וְהַמְפֹאָר וְהַמִּתְנַשֵּׂא מִימוֹת עוֹלָם. אֱלֹהֵי עוֹלָם, בְּרַחֲמֶיךָ הָרַבִּים רַחֵם עָלֵינוּ, אֲדוֹן עֻזֵּנוּ, צוּר מִשְׂגַּבֵּנוּ, מָגֵן יִשְׁ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrachotBeforeShmaShacharit1 {
            get {
                return ResourceManager.GetString("BrachotBeforeShmaShacharit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לָאֵל בָּרוּךְ נְעִימוֹת יִתֵּנוּ, לָמֶלֶךְ אֵל חַי וְקַיָּם זְמִירוֹת יֹאמֵרוּ וְתֻשְׁבָּחוֹת יַשְׁמִיעוּ, כִּי הוּא לְבַדּוֹ פּוֹעֵל גְּבוּרוֹת, עוֹשֶׂה חֲדָשׁוֹת, בַּעַל מִלְחָמוֹת, זוֹרֵעַ צְדָקוֹת, מַצְמִיחַ יְשׁוּעוֹת, בּוֹרֵא רְפוּאוֹת, נוֹרָא תְהִלּוֹת, אֲדוֹן הַנִּפְלָאוֹת, הַמְחַדֵּשׁ בְּטוּבוֹ בְּכָל יוֹם תָּמִיד מַעֲשֵׂה בְרֵאשִׁית. כָּאָמוּר: לְעֹשֵׂה אוֹרִים גְּדֹלִים, כִּי לְעוֹלָם חַסְדּוֹ. אוֹר חָדָשׁ עַל צִיּוֹן תָּאִיר וְנִזְכֶּה כֻלָּנוּ מְהֵרָה לְאוֹרוֹ. בָּרוּךְ אַתָּה יְיָ, יוֹצֵר הַמ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrachotBeforeShmaShacharit2 {
            get {
                return ResourceManager.GetString("BrachotBeforeShmaShacharit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אַהֲבָה רַבָּה אֲהַבְתָּנוּ, יְיָ אֱלֹהֵינוּ, חֶמְלָה גְדוֹלָה וִיתֵרָה חָמַלְתָּ עָלֵינוּ. אָבִינוּ מַלְכֵּנוּ, בַּעֲבוּר אֲבוֹתֵינוּ שֶׁבָּטְחוּ בְךָ וַתְּלַמְּדֵם חֻקֵּי חַיִּים, כֵּן תְּחָנֵּנוּ וּתְלַמְּדֵנוּ. אָבִינוּ, אָב הָרַחֲמָן הַמְרַחֵם, רַחֵם עָלֵינוּ וְתֵן בְּלִבֵּנוּ לְהָבִין וּלְהַשְׂכִּיל, לִשְׁמֹעַ, לִלְמֹד וּלְלַמֵּד, לִשְׁמֹר וְלַעֲשׂוֹת וּלְקַיֵּם אֶת כָּל דִּבְרֵי תַלְמוּד תּוֹרָתֶךָ בְּאַהֲבָה. וְהָאֵר עֵינֵינוּ בְּתוֹרָתֶךָ, וְדַבֵּק לִבֵּנוּ בְּמִצְוֹתֶיךָ, וְיַחֵד לְבָבֵנוּ לְאַהֲב [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrachotBeforeShmaShacharit3 {
            get {
                return ResourceManager.GetString("BrachotBeforeShmaShacharit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לפני הנחת תפילין של יד אומר:
        ///בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, אֲשֶׁר קִדְּשָׁנוּ בְּמִצְוֹתָיו וְצִוָּנוּ לְהָנִיחַ תְּפִלִּין.
        ///
        ///לפני הנחת תפילין של ראש אומר:
        ///בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, אֲשֶׁר קִדְּשָׁנוּ בְּמִצְוֹתָיו וְצִוָּנוּ עַל מִצְוַת תְּפִלִּין.
        ///
        ///יהדק את רצועת הראש ויאמר מיד:
        ///בָּרוּךְ שֵׁם כְּבוֹד מַלְכוּתוֹ לְעוֹלָם וָעֶד.
        ///
        ///וּמֵחָכְמָתְךָ אֵל עֶלְיוֹן תַּאֲצִיל עָלַי, וּמִבִּינָתְךָ תְּבִינֵנִי. וּבְחַסְדְּךָ תַּגְדִּיל עָלַי, וּבִגְבוּרָתְךָ תַּצְמִית [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HanachatTfillin {
            get {
                return ResourceManager.GetString("HanachatTfillin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, אֲשֶׁר קִדְּשָׁנוּ בְּמִצְוֹתָיו וְצִוָּנוּ לְהַדְלִיק נֵר שֶׁל חֲנֻכָּה.
        ///
        ///בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, שֶׁעָשָׂה נִסִּים לַאֲבוֹתֵינוּ בַּיָּמִים הָהֵם בַּזְּמַן הַזֶּה..
        /// </summary>
        public static string HannukahCandlesBlessing {
            get {
                return ResourceManager.GetString("HannukahCandlesBlessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יִתְגַּדֵּל וְיִתְקַדֵּשׁ שְׁמֵהּ רַבָּא (עונים: אמן), בְּעָלְמָא דִּי בְרָא כִרְעוּתֵהּ, וְיַמְלִיךְ מַלְכוּתֵהּ בְּחַיֵּיכוֹן וּבְיוֹמֵיכוֹן וּבְחַיֵּי דְכָל בֵּית יִשְׂרָאֵל, בַּעֲגָלָא וּבִזְמַן קָרִיב, וְאִמְרוּ אָמֵן.
        ///
        ///(גם הקהל אומר:) יְהֵא שְׁמֵהּ רַבָּא מְבָרַךְ לְעָלַם וּלְעָלְמֵי עָלְמַיָּא.
        ///
        ///יִתְבָּרַךְ וְיִשְׁתַּבַּח וְיִתְפָּאַר וְיִתְרוֹמַם וְיִתְנַשֵּׂא וְיִתְהַדָּר וְיִתְעַלֶּה וְיִתְהַלָּל שְׁמֵהּ דְקֻדְשָׁא בְּרִיךְ הוּא (עונים: בְּרִיךְ הוּא). לְעֵלָּא {0} בִּרְכָתָא וְשִׁירָתָא תֻּשׁ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HaziKadish {
            get {
                return ResourceManager.GetString("HaziKadish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יִתְגַּדֵּל וְיִתְקַדֵּשׁ שְׁמֵהּ רַבָּא (עונים: אמן), בְּעָלְמָא דִּי בְרָא כִרְעוּתֵהּ, וְיַמְלִיךְ מַלְכוּתֵהּ בְּחַיֵּיכוֹן וּבְיוֹמֵיכוֹן וּבְחַיֵּי דְכָל בֵּית יִשְׂרָאֵל, בַּעֲגָלָא וּבִזְמַן קָרִיב, וְאִמְרוּ אָמֵן.
        ///
        ///(גם הקהל אומר:) יְהֵא שְׁמֵהּ רַבָּא מְבָרַךְ לְעָלַם וּלְעָלְמֵי עָלְמַיָּא.
        ///
        ///יִתְבָּרַךְ וְיִשְׁתַּבַּח וְיִתְפָּאַר וְיִתְרוֹמַם וְיִתְנַשֵּׂא וְיִתְהַדָּר וְיִתְעַלֶּה וְיִתְהַלָּל שְׁמֵהּ דְקֻדְשָׁא בְּרִיךְ הוּא (עונים: בְּרִיךְ הוּא). לְעֵלָּא {0} בִּרְכָתָא וְשִׁירָתָא תֻּשׁ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KadishDerabanan {
            get {
                return ResourceManager.GetString("KadishDerabanan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יִתְגַּדֵּל וְיִתְקַדֵּשׁ שְׁמֵהּ רַבָּא (עונים: אמן), בְּעָלְמָא דִּי בְרָא כִרְעוּתֵהּ, וְיַמְלִיךְ מַלְכוּתֵהּ בְּחַיֵּיכוֹן וּבְיוֹמֵיכוֹן וּבְחַיֵּי דְכָל בֵּית יִשְׂרָאֵל, בַּעֲגָלָא וּבִזְמַן קָרִיב, וְאִמְרוּ אָמֵן.
        ///
        ///(גם הקהל אומר:) יְהֵא שְׁמֵהּ רַבָּא מְבָרַךְ לְעָלַם וּלְעָלְמֵי עָלְמַיָּא.
        ///
        ///יִתְבָּרַךְ וְיִשְׁתַּבַּח וְיִתְפָּאַר וְיִתְרוֹמַם וְיִתְנַשֵּׂא וְיִתְהַדָּר וְיִתְעַלֶּה וְיִתְהַלָּל שְׁמֵהּ דְקֻדְשָׁא בְּרִיךְ הוּא (עונים: בְּרִיךְ הוּא). לְעֵלָּא {0} בִּרְכָתָא וְשִׁירָתָא תֻּשׁ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KadishShalem {
            get {
                return ResourceManager.GetString("KadishShalem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יִתְגַּדֵּל וְיִתְקַדֵּשׁ שְׁמֵהּ רַבָּא (עונים: אמן), בְּעָלְמָא דִּי בְרָא כִרְעוּתֵהּ, וְיַמְלִיךְ מַלְכוּתֵהּ בְּחַיֵּיכוֹן וּבְיוֹמֵיכוֹן וּבְחַיֵּי דְכָל בֵּית יִשְׂרָאֵל, בַּעֲגָלָא וּבִזְמַן קָרִיב, וְאִמְרוּ אָמֵן.
        ///
        ///(גם הקהל אומר:) יְהֵא שְׁמֵהּ רַבָּא מְבָרַךְ לְעָלַם וּלְעָלְמֵי עָלְמַיָּא.
        ///
        ///יִתְבָּרַךְ וְיִשְׁתַּבַּח וְיִתְפָּאַר וְיִתְרוֹמַם וְיִתְנַשֵּׂא וְיִתְהַדָּר וְיִתְעַלֶּה וְיִתְהַלָּל שְׁמֵהּ דְקֻדְשָׁא בְּרִיךְ הוּא (עונים: בְּרִיךְ הוּא). לְעֵלָּא {0} בִּרְכָתָא וְשִׁירָתָא תֻּשׁ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KadishYatom {
            get {
                return ResourceManager.GetString("KadishYatom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קַוֵּה אֶל יְיָ, חֲזַק וְיַאֲמֵץ לִבֶּךָ, וְקַוֵּה אֶל יְיָ. אֵין קָדוֹשׁ כַּיְיָ, כִּי אֵין בִּלְתֶּךָ, וְאֵין צוּר כֵּאלֹהֵינוּ. כִּי מִי אֱלוֹהַּ מִבַּלְעֲדֵי יְיָ, וּמִי צוּר זוּלָתִי אֱלֹהֵינוּ.
        ///
        ///אֵין כֵּאלֹהֵינוּ, אֵין כַּאדוֹנֵינוּ, אֵין כְּמַלְכֵּנוּ, אֵין כְּמוֹשִׁיעֵנוּ. מִי כֵאלֹהֵינוּ, מִי כַאדוֹנֵינוּ, מִי כְמַלְכֵּנוּ, מִי כְמוֹשִׁיעֵנוּ. נוֹדֶה לֵאלֹהֵינוּ, נוֹדֶה לַאדוֹנֵינוּ, נוֹדֶה לְמַלְכֵּנוּ, נוֹדֶה לְמוֹשִׁיעֵנוּ. בָּרוּךְ אֱלֹהֵינוּ, בָּרוּךְ אֲדוֹנֵינוּ, בָּרוּךְ מַלְכֵּנוּ, בָּרוּ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KavehElHashem {
            get {
                return ResourceManager.GetString("KavehElHashem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נְקַדֵּשׁ אֶת שִׁמְךָ בָּעוֹלָם, כְּשֵׁם שֶׁמַּקְדִּישִׁים אוֹתוֹ בִּשְׁמֵי מָרוֹם, כַּכָּתוּב עַל יַד נְבִיאֶךָ וְקָרָא זֶה אֶל זֶה וְאָמַר: 
        ///קָדוֹשׁ קָדוֹשׁ קָדוֹשׁ יְיָ צְבָאוֹת. מְלֹא כָל הָאָרֶץ כְּבוֹדוֹ. לְעֻמָּתָם בָּרוּךְ יֹאמֵרוּ: 
        ///בָּרוּךְ כְּבוֹד יְיָ מִמְּקוֹמוֹ. וּבְדִבְרֵי קָדְשְׁךָ כָּתוּב לֵאמֹר: 
        ///יִמְלֹךְ יְיָ לְעוֹלָם. אֱלֹהַיִךְ צִיּוֹן לְדֹר וָדֹר הַלְלוּיָהּ.
        ///לְדוֹר וָדוֹר נַגִּיד גָּדְלֶךָ וּלְנֵצַח נְצָחִים קְדֻשָּׁתְךָ נַקְדִּישׁ. וְשִׁבְחֲךָ אֱלֹהֵינוּ מִפִּינוּ לֹא יָמוּשׁ לְע [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Kdusha {
            get {
                return ResourceManager.GetString("Kdusha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נְקַדֵּשׁ אֶת שִׁמְךָ בָּעוֹלָם כְּשֵׁם שֶׁמַקְדִּישִׁים  אוֹתוֹ בִּשְׁמֵי מָרוֹם, כַּכָּתוּב עַל יַד נְבִיאֶךָ: 
        ///וְקָרָא זֶה אֶל זֶה וְאָמַר:
        ///קָדוֹשׁ, קָדוֹשׁ, קָדוֹשׁ יְיָ צְבָאוֹת, מְלֹא כָל הָאָרֶץ כְּבוֹדוֹ. לְעֻמָּתָם בָּרוּךְ יֹאמֵרוּ:  
        ///בָּרוּךְ כְּבוֹד יְיָ מִמְּקוֹמוֹ. וּבְדִבְרֵי קָדְשְׁךָ כָּתוּב לֵאמֹר:
        ///יִמְלֹךְ יְיָ לְעוֹלָם, אֱלֹהַיִךְ צִיּוֹן לְדֹר וָדֹר, הַלְלוּיָה.
        ///לְדוֹר וָדוֹר נַגִיד גָּדְלֶךָ וּלְנֵצַח נְצָחִים קְדֻשָּׁתְךָ נַקְדִּישׁ, וְשִׁבְחֲךָ אֱלֹהֵינוּ מִפִּינוּ לֹא יָמוּש לְעוֹלָם וָעֶד, כִּי אֵל [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KdushatKeter {
            get {
                return ResourceManager.GetString("KdushatKeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בָּרוּךְ אַתָּה יְיָ אֱלֹהֵינוּ מֶלֶךְ הָעוֹלָם, {0} וְעַל תְּנוּבַת הַשָּׂדֶה וְעַל אֶרֶץ חֶמְדָּה טוֹבָה וּרְחָבָה, שֶׁרָצִיתָ וְהִנְחַלְתָּ לַאֲבוֹתֵינוּ לֶאֱכֹל מִפִּרְיָהּ וְלִשְׂבֹּעַ מִטּוּבָהּ. רַחֵם יְיָ אֱלֹהֵינוּ עַל יִשְׂרָאֵל עַמֶּךָ וְעַל יְרוּשָׁלַיִם עִירֶךָ וְעַל צִיּוֹן מִשְׁכַּן כְּבוֹדֶךָ וְעַל מִזְבַּחֲךָ וְעַל הֵיכָלֶךָ. וּבְנֵה יְרוּשָׁלַיִם עִיר הַקֹּדֶשׁ בִּמְהֵרָה בְיָמֵינוּ, וְהַעֲלֵנוּ לְתוֹכָהּ וְשַׂמְּחֵנוּ בְּבִנְיָנָהּ וְנֹאכַל מִפִּרְיָהּ וְנִשְׂבַּע מִטּוּבָהּ, וּנְבָרֶכְךָ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MeeinShalosh {
            get {
                return ResourceManager.GetString("MeeinShalosh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוֹדִים אֲנַחְנוּ לָךְ שָׁאַתָּה הוּא יְיָ אֱלֹהֵינוּ וֵאלֹהֵי אֲבוֹתֵינוּ לְעוֹלָם וָעֶד, צוּר חַיֵּינוּ, מָגֵן יִשְׁעֵנוּ אַתָּה הוּא לְדוֹר וָדוֹר. נוֹדֶה לְּךָ וּנְסַפֵּר תְּהִלָּתֶךָ עַל חַיֵּינוּ הַמְּסוּרִים בְּיָדֶיךָ, וְעַל נִשְׁמוֹתֵינוּ הַפְּקוּדוֹת לָךְ, וְעַל נִסֶּיךָ שֶׁבְּכָל יוֹם עִמָּנוּ, וְעַל נִפְלְאוֹתֶיךָ וְטוֹבוֹתֶיךָ שֶׁבְּכָל עֵת, עֶרֶב וָבֹקֶר וְצָהֳרָיִם. הַטּוֹב כִּי לֹא כָלוּ רַחֲמֶיךָ, וְהַמְּרַחֵם כִּי לֹא תַמּוּ חֲסָדֶיךָ, מֵעוֹלָם קִוִּינוּ לָךְ..
        /// </summary>
        public static string Modim {
            get {
                return ResourceManager.GetString("Modim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אֱלֹהֵינוּ וֵאלֹהֵי אֲבוֹתֵינוּ, מֶלֶךְ רַחֲמָן, רַחֵם עָלֵינוּ, טוֹב וּמֵטִיב הִדָּרֶשׁ לָנוּ, שׁוּבָה עָלֵינוּ בַּהֲמוֹן רַחֲמֶיךָ בִּגְלַל אָבוֹת שֶׁעָשׂוּ רְצוֹנֶךָ. בְּנֵה בֵיתְךָ כְּבַתְּחִלָּה וְכוֹנֵן מִקְדָּשְׁךָ עַל מְכוֹנוֹ, וְהַרְאֵנוּ בְּבִנְיָנוֹ וְשַׂמְּחֵנוּ בְּתִקּוּנוֹ, וְהָשֵׁב כֹּהֲנִים לַעֲבוֹדָתָם וּלְוִיִּם לְשִׁירָם וּלְזִמְרָם, וְהָשֵׁב יִשְׂרָאֵל לִנְוֵיהֶם. וְשָׁם נַעֲלֶה וְנֵרָאֶה וְנִשְׁתַּחֲוֶה לְפָנֶיךָ בְּשָׁלֹשׁ פַּעֲמֵי רְגָלֵינוּ, כַּכָּתוּב בְּתוֹרָתֶךָ: שָׁלֹשׁ פְּעָמִים [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MusasfCholHamoed3 {
            get {
                return ResourceManager.GetString("MusasfCholHamoed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רָאשֵׁי חֳדָשִׁים לְעַמְּךָ נָתַתָּ, זְמַן כַּפָּרָה לְכָל תּוֹלְדוֹתָם, בִּהְיוֹתָם מַקְרִיבִים לְפָנֶיךָ זִבְחֵי רָצוֹן, וּשְׂעִירֵי חַטָּאת לְכַפֵּר בַּעֲדָם. זִכָּרוֹן לְכֻלָּם יִהְיוּ, וּתְשׁוּעַת נַפְשָׁם מִיַּד שׂוֹנֵא. מִזְבֵּחַ חָדָשׁ בְּצִיּוֹן תָּכִין, וְעוֹלַת רֹאשׁ חֹדֶשׁ נַעֲלֶה עָלָיו וּשְׂעִירֵי עִזִּים נַעֲשֶׂה בְרָצוֹן, וּבַעֲבוֹדַת בֵּית הַמִּקְדָּשׁ נִשְׂמַח כֻּלָּנוּ, וְשִׁירֵי דָוִד עַבְדְּךָ נִשְׁמָעִים בְּעִירֶךָ הָאֲמוּרִים לִפְנֵי מִזְבְּחֶךָ, אַהֲבַת עוֹלָם תָּבִיא לָהֶם וּבְרִית אָבוֹת לַבָּנִים תִּזְכֹּר. וַהֲבִיאֵנוּ לְצִיּוֹן עִירְךָ בְּרִנָּה ו [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MussafRoshChodeshSE1 {
            get {
                return ResourceManager.GetString("MussafRoshChodeshSE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אֱלֹהֵינוּ וֵאלֹהֵי אֲבוֹתֵינוּ, חַדֵּשׁ עָלֵינוּ אֶת הַחֹדֶשׁ הַזֶּה לְטוֹבָה וְלִבְרָכָה, לְשָׂשׂוֹן וּלְשִׂמְחָה, לִישׁוּעָה וּלְנֶחָמָה, לְפַרְנָסָה וּלְכַלְכָּלָה, לְחַיִּים וּלְשָׁלוֹם, לִמְחִילַת חֵטְא וְלִסְלִיחַת עָוֹן{0}, כִּי בְעַמְּךָ יִשְׂרָאֵל בָּחַרְתָּ מִכָּל הָאֻמּוֹת וְחֻקֵּי רָאשֵׁי חֳדָשִׁים לָהֶם קָבָעְתָּ. בָּרוּךְ אַתָּה יְיָ, מְקַדֵּשׁ יִשְׂרָאֵל וְרָאשֵׁי חֳדָשִׁים..
        /// </summary>
        public static string MussafRoshChodeshSE2 {
            get {
                return ResourceManager.GetString("MussafRoshChodeshSE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שְׁנֵי.
        /// </summary>
        public static string OmerCount2 {
            get {
                return ResourceManager.GetString("OmerCount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הַיּוֹם {0} יָמִים לָעֹמֶר.
        /// </summary>
        public static string OmerShort {
            get {
                return ResourceManager.GetString("OmerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הַיּוֹם יוֹם אֶחָד לָעֹמֶר.
        /// </summary>
        public static string OmerShort1 {
            get {
                return ResourceManager.GetString("OmerShort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יְבָרֶכְךָ יְיָ וְיִשְׁמְרֶךָ. יָאֵר יְיָ פָּנָיו אֵלֶיךָ וִיחֻנֶּךָּ. יִשָּׂא יְיָ פָּנָיו אֵלֶיךָ וְיָשֵׂם לְךָ שָׁלוֹם.
        ///
        ///אֵלּוּ דְבָרִים שֶׁאֵין לָהֶם שִׁעוּר: הַפֵּאָה וְהַבִּכּוּרִים וְהָרֵאָיוֹן וּגְמִילוּת חֲסָדִים וְתַלְמוּד תּוֹרָה.
        ///
        ///אֵלּוּ דְבָרִים שֶׁאָדָם אוֹכֵל פֵּרוֹתֵיהֶם בָּעוֹלָם הַזֶּה, וְהַקֶּרֶן קַיֶּמֶת לָעוֹלָם הַבָּא, וְאֵלּוּ הֵן: כִּבּוּד אָב וָאֵם, וּגְמִילוּת חֲסָדִים, וְהַשְׁכָּמַת בֵּית הַמִּדְרָשׁ שַׁחֲרִית וְעַרְבִית, וְהַכְנָסַת אוֹרְחִים, וּבִקּוּר חוֹלִים, וְהַכְנָסַת כ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ParashatBirkatCohanim {
            get {
                return ResourceManager.GetString("ParashatBirkatCohanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פִּטּוּם הַקְּטֹרֶת: הַצֳּרִי וְהַצִּפּוֹרֶן, הַחֶלְבְּנָה וְהַלְּבוֹנָה, מִשְׁקַל שִׁבְעִים שִׁבְעִים מָנֶה, מֹר, וּקְצִיעָה, שִׁבֹּלֶת נֵרְדְּ, וְכַרְכֹּם, מִשְׁקַל שִׁשָּׁה עָשָׂר שִׁשָּׁה עָשָׂר מָנֶה, הַקֹשְׂטְ שְׁנֵים עָשָׂר, וְקִלּוּפָה שְׁלֹשָׁה, וְקִנָּמוֹן תִּשְׁעָה. בֹּרִית כַּרְשִׁינָה תִּשְׁעָה קַבִּין, יֵין קַפְרִיסִין סְאִין תְּלָתָא וְקַבִּין תְּלָתָא, וְאִם אֵין לוֹ יֵין קַפְרִיסִין מֵבִיא חֲמַר חִוַּרְיָן עַתִּיק. 
        ///מֶלַח סְדוֹמִית רֹבַע, מַעֲלֶה עָשָׁן כָּל שֶׁהוּא. רַבִּי נָתָן הַבַּבְלִ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PitumHaktoret1 {
            get {
                return ResourceManager.GetString("PitumHaktoret1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תַּנְיָא רַבִּי נָתָן אוֹמֵר: כְּשֶׁהוּא שׁוֹחֵק אוֹמֵר: הָדֵק הֵיטֵב, הֵיטֵב הָדֵק, מִפְּנֵי שֶׁהַקּוֹל יָפֶה לַבְּשָׂמִים. פִּטְּמָהּ לַחֲצָאִין כְּשֵׁרָה, לִשְׁלִישׁ וְלִרְבִיעַ לֹא שָׁמַעְנוּ. אָמַר רַבִּי יְהוּדָה: זֶה הַכְּלָל: אִם כְּמִדָּתָהּ כְּשֵׁרָה לַחֲצָאִין, וְאִם חִסַּר אַחַת מִכָּל סַמָּנֶיהָ חַיָּב מִיתָה. תַּנְיָא בַּר קַפָּרָא אוֹמֵר: אַחַת לְשִׁשִּׁים אוֹ לְשִׁבְעִים שָׁנָה הָיְתָה בָאָה שֶׁל שִׁירַיִם לַחֲצָאִין. וְעוֹד תָּנֵי בַּר קַפָּרָא: אִלּוּ הָיָה נוֹתֵן בָּהּ קוֹרְטוֹב שֶׁל דְּב [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PitumHaktoret2 {
            get {
                return ResourceManager.GetString("PitumHaktoret2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שלוש פעמים: יְיָ צְבָאוֹת עִמָּנוּ, מִשְׂגַּב לָנוּ אֱלֹהֵי יַעֲקֹב סֶלָה. 
        ///שלוש פעמים: יְיָ צְבָאוֹת, אַשְׁרֵי אָדָם בֹּטֵחַ בָּךְ.
        ///שלוש פעמים: יְיָ הוֹשִׁיעָה, הַמֶּלֶךְ יַעֲנֵנוּ בְיוֹם קָרְאֵנוּ. 
        ///אַתָּה סֵתֶר לִי מִצַּר תִצְּרֵנִי, רָנֵּי פַלֵּט תְּסוֹבְבֵנִי סֶלָה. וְעָרְבָה לַיְיָ מִנְחַת יְהוּדָה וִירוּשָׁלָיִם כִּימֵי עוֹלָם וּכְשָׁנִים קַדְמוֹנִיּוֹת..
        /// </summary>
        public static string PitumHaktoret3 {
            get {
                return ResourceManager.GetString("PitumHaktoret3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אַתָּה קָדוֹשׁ וְשִׁמְךָ קָדוֹשׁ, וּקְדוֹשִׁים בְּכָל יוֹם יְהַלְלוּךָ סֶּלָה. בָּרוּךְ אַתָּה יְיָ, {0} הַקָּדוֹשׁ..
        /// </summary>
        public static string SE03 {
            get {
                return ResourceManager.GetString("SE03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אַתָּה חוֹנֵן לְאָדָם דַּעַת וּמְלַמֵּד לֶאֱנוֹשׁ בִּינָה. {0}חָנֵּנוּ מֵאִתְּךָ דֵּעָה בִּינָה וְהַשְׂכֵּל. בָּרוּךְ אַתָּה יְיָ, חוֹנֵן הַדָּעַת..
        /// </summary>
        public static string SE04 {
            get {
                return ResourceManager.GetString("SE04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סְלַח לָנוּ אָבִינוּ כִּי חָטָאנוּ, מְחַל לָנוּ מַלְכֵּנוּ כִּי פָשָׁעְנוּ, כִּי מוֹחֵל וְסוֹלֵחַ אָתָּה. בָּרוּךְ אַתָּה יְיָ, חַנּוּן הַמַּרְבֶּה לִסְלוֹחַ..
        /// </summary>
        public static string SE06 {
            get {
                return ResourceManager.GetString("SE06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רְאֵה נָא בְעָנְיֵנוּ, וְרִיבָה רִיבֵנוּ, וּגְאָלֵנוּ מְהֵרָה לְמַעַן שְׁמֶךָ, כִּי אֵל גּוֹאֵל חָזָק אָתָּה. בָּרוּךְ אַתָּה יְיָ, גּוֹאֵל יִשְׂרָאֵל..
        /// </summary>
        public static string SE07 {
            get {
                return ResourceManager.GetString("SE07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בָּרֵךְ עָלֵינוּ יְיָ אֱלֹהֵינוּ אֶת הַשָּׁנָה הַזֹּאת וְאֶת כָּל מִינֵי תְבוּאָתָהּ לְטוֹבָה, וְתֵן {0} עַל פְּנֵי הָאֲדָמָה וְשַׂבְּעֵנוּ מִטּוּבָהּ, וּבָרֵךְ שְׁנָתֵנוּ כַּשָּׁנִים הַטּוֹבוֹת. בָּרוּךְ אַתָּה יְיָ, מְבָרֵךְ הַשָּׁנִים..
        /// </summary>
        public static string SE09 {
            get {
                return ResourceManager.GetString("SE09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תְּקַע בְּשׁוֹפָר גָּדוֹל לְחֵרוּתֵנוּ, וְשָׂא נֵס לְקַבֵּץ גָּלֻיּוֹתֵינוּ, וְקַבְּצֵנוּ יַחַד מֵאַרְבַּע כַּנְפוֹת הָאָרֶץ. בָּרוּךְ אַתָּה יְיָ, מְקַבֵּץ נִדְחֵי עַמּוֹ יִשְׂרָאֵל..
        /// </summary>
        public static string SE10 {
            get {
                return ResourceManager.GetString("SE10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הָשִׁיבָה שׁוֹפְטֵינוּ כְּבָרִאשׁוֹנָה, וְיוֹעֲצֵינוּ כְּבַתְּחִלָּה, וְהָסֵר מִמֶּנוּ יָגוֹן וַאֲנָחָה, וּמְלֹךְ עָלֵינוּ אַתָּה יְיָ לְבַדְּךָ בְּחֶסֶד וּבְרַחֲמִים, וְצַדְּקֵנוּ בַּמִּשְׁפָּט. בָּרוּךְ אַתָּה יְיָ, {0}..
        /// </summary>
        public static string SE11 {
            get {
                return ResourceManager.GetString("SE11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וְלַמַּלְשִׁינִים אַל תְּהִי תִקְוָה, וְכָל הָרִשְׁעָה כְּרֶגַע תֹּאבֵד, וְכָל אֹיְבֶיךָ מְהֵרָה יִכָּרֵתוּ, וְהַזֵּדִים מְהֵרָה תְעַקֵּר וּתְשַׁבֵּר וּתְמַגֵּר וְתַכְנִיעַ בִּמְהֵרָה בְיָמֵינוּ. בָּרוּךְ אַתָּה יְיָ, שׁוֹבֵר אוֹיְבִים וּמַכְנִיעַ זֵדִים..
        /// </summary>
        public static string SE12 {
            get {
                return ResourceManager.GetString("SE12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עַל הַצַּדִּיקִים וְעַל הַחֲסִידִים וְעַל זִקְנֵי עַמְּךָ בֵית יִשְׂרָאֵל וְעַל פְּלֵיטַת סוֹפְרֵיהֶם וְעַל גֵּרֵי הַצֶּדֶק וְעָלֵינוּ, יֶהֱמוּ רַחֲמֶיךָ יְיָ אֱלֹהֵינוּ, וְתֵן שָׂכָר טוֹב לְכָל הַבּוֹטְחִים בְּשִׁמְךָ בֶּאֱמֶת, וְשִׂים חֶלְקֵנוּ עִמָּהֶם לְעוֹלָם וְלֹא נֵבוֹשׁ כִּי בְךָ בָטָחְנוּ. בָּרוּךְ אַתָּה יְיָ, מִשְׁעָן וּמִבְטָח לַצַּדִּיקִים..
        /// </summary>
        public static string SE13 {
            get {
                return ResourceManager.GetString("SE13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וְלִירוּשָׁלַיִם עִירְךָ בְּרַחֲמִים תָּשׁוּב, וְתִשְׁכֹּן בְּתוֹכָהּ כַּאֲשֶׁר דִּבַּרְתָּ, וּבְנֵה אוֹתָהּ בְּקָרוֹב בְּיָמֵינוּ בִּנְיַן עוֹלָם, וְכִסֵּא דָּוִד מְהֵרָה לְתוֹכָהּ תָּכִין. {0}.
        /// </summary>
        public static string SE14 {
            get {
                return ResourceManager.GetString("SE14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שְׁמַע קוֹלֵנוּ יְיָ אֱלֹהֵינוּ, חוּס וְרַחֵם עָלֵינוּ, וְקַבֵּל בְּרַחֲמִים וּבְרָצוֹן אֶת תְּפִלָּתֵנוּ, כִּי אֵל שׁוֹמֵעַ תְּפִלּוֹת וְתַחֲנוּנִים אָתָּה, וּמִלְּפָנֶיךָ מַלְכֵּנוּ רֵיקָם אַל תְּשִׁיבֵנוּ,.
        /// </summary>
        public static string SE16 {
            get {
                return ResourceManager.GetString("SE16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כִּי אַתָּה שׁוֹמֵעַ תְּפִלַּת עַמְּךָ יִשְׂרָאֵל, בְּרַחֲמִים. בָּרוּךְ אַתָּה יְיָ, שׁוֹמֵעַ תְּפִלָּה..
        /// </summary>
        public static string SE16B {
            get {
                return ResourceManager.GetString("SE16B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רְצֵה יְיָ אֱלֹהֵינוּ בְּעַמְּךָ יִשְׂרָאֵל וּבִתְפִלָּתָם, וְהָשֵׁב אֶת הָעֲבוֹדָה לִדְבִיר בֵּיתֶךָ, וְאִשֵּׁי יִשְׂרָאֵל וּתְפִלָּתָם בְּאַהֲבָה תְקַבֵּל בְּרָצוֹן, וּתְהִי לְרָצוֹן תָּמִיד עֲבוֹדַת יִשְׂרָאֵל עַמֶּךָ..
        /// </summary>
        public static string SE17 {
            get {
                return ResourceManager.GetString("SE17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וְתֶחֱזֶינָה עֵינֵינוּ בְּשׁוּבְךָ לְצִיּוֹן בְּרַחֲמִים. בָּרוּךְ אַתָּה יְיָ, הַמַּחֲזִיר שְׁכִינָתוֹ לְצִיּוֹן..
        /// </summary>
        public static string SE17B {
            get {
                return ResourceManager.GetString("SE17B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וְעַל כֻּלָּם יִתְבָּרַךְ וְיִתְרוֹמַם שִׁמְךָ מַלְכֵּנוּ תָּמִיד לְעוֹלָם וָעֶד.{0} וְכֹל הַחַיִּים יוֹדוּךָ סֶּלָה, וִיהַלְלוּ אֶת שִׁמְךָ בֶּאֱמֶת, הָאֵל יְשׁוּעָתֵנוּ וְעֶזְרָתֵנוּ סֶלָה. בָּרוּךְ אַתָּה יְיָ, הַטּוֹב שִׁמְךָ וּלְךָ נָאֶה לְהוֹדוֹת..
        /// </summary>
        public static string SE18 {
            get {
                return ResourceManager.GetString("SE18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שָׁלוֹם רָב עַל יִשְׂרָאֵל עַמְּךָ תָּשִׂים לְעוֹלָם, כִּי אַתָּה הוּא מֶלֶךְ אָדוֹן לְכָל הַשָּׁלוֹם. וְטוֹב בְּעֵינֶיךָ לְבָרֵךְ אֶת עַמְּךָ יִשְׂרָאֵל בְּכָל עֵת וּבְכָל שָׁעָה בִּשְׁלוֹמֶךָ.{0} בָּרוּךְ אַתָּה יְיָ, הַמְבָרֵךְ אֶת עַמּוֹ יִשְׂרָאֵל בַּשָּׁלוֹם..
        /// </summary>
        public static string SE19_ShalomRav {
            get {
                return ResourceManager.GetString("SE19_ShalomRav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  בְּסֵפֶר חַיִּים, בְּרָכָה וְשָׁלוֹם, וּפַרְנָסָה טוֹבָה, נִזָּכֵר וְנִכָּתֵב לְפָנֶיךָ, אֲנַחְנוּ וְכָל עַמְּךָ בֵּית יִשְׂרָאֵל, לְחַיִּים טוֹבִים וּלְשָׁלוֹם..
        /// </summary>
        public static string SE19AYT {
            get {
                return ResourceManager.GetString("SE19AYT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to וְהוּא רַחוּם יְכַפֵּר עָוֹן וְלֹא יַשְׁחִית, וְהִרְבָּה לְהָשִׁיב אַפּוֹ וְלֹא יָעִיר כָּל חֲמָתוֹ. אַתָּה יְיָ, לֹא תִכְלָא רַחֲמֶיךָ מִמֶּנּוּ, חַסְדְּךָ וַאֲמִתְּךָ תָּמִיד יִצְּרוּנוּ. הוֹשִׁיעֵנוּ יְיָ אֱלֹהֵינוּ וְקַבְּצֵנוּ מִן הַגּוֹיִם, לְהוֹדוֹת לְשֵׁם קָדְשֶׁךָ, לְהִשְׁתַּבֵּחַ בִּתְהִלָּתֶךָ. אִם עֲוֹנוֹת תִּשְׁמָר־יָהּ, אֲדֹנָי מִי יַעֲמֹד. כִּי עַמְּךָ הַסְּלִיחָה לְמַעַן תִּוָּרֵא. לֹא כַחֲטָאֵינוּ תַּעֲשֶׂה־לָנוּ וְלֹא כַעֲוֹנֹתֵינוּ תִגְמֹל עָלֵינוּ. אִם עֲוֹנֵינוּ עָנוּ בָנוּ, יְיָ, עֲשֵׂ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TachanunBH1 {
            get {
                return ResourceManager.GetString("TachanunBH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אָבִינוּ אָב הָרַחֲמָן, הַרְאֵנוּ אוֹת לְטוֹבָה וְקַבֵּץ נְפוּצוֹתֵינוּ מֵאַרְבַּע כַּנְפוֹת הָאָרֶץ. יַכִּירוּ וְיֵדְעוּ כָּל הַגּוֹיִם, כִּי אַתָּה יְיָ אֱלֹהֵינוּ. וְעַתָּה יְיָ אָבִינוּ אָתָּה, אֲנַחְנוּ הַחֹמֶר וְאַתָּה יֹצְרֵנוּ וּמַעֲשֵׂה יָדְךָ כֻּלָּנוּ. הוֹשִׁיעֵנוּ לְמַעַן שְׁמֶךָ, צוּרֵנוּ מַלְכֵּנוּ וְגוֹאֲלֵנוּ. חוּסָה יְיָ עַל עַמֶּךָ וְאַל תִּתֵּן נַחֲלָתְךָ לְחֶרְפָּה לִמְשָׁל־בָּם גּוֹיִם, לָמָּה יֹאמְרוּ בָעַמִּים אַיֵּה אֱלֹהֵיהֶם. יָדַעְנוּ כִּי חָטָאנוּ וְאֵין מִי יַעֲמֹד בַּעֲדֵנוּ, ש [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TachanunBH3 {
            get {
                return ResourceManager.GetString("TachanunBH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הַבֶּט־נָא רַחֶם־נָא עַל עַמְּךָ מְהֵרָה לְמַעַן שְׁמֶךָ. בְּרַחֲמֶיךָ הָרַבִּים יְיָ אֱלֹהֵינוּ חוּס וְרַחֵם וְהוֹשִׁיעָה צֹאן מַרְעִיתֶךָ. וְאַל יִמְשָׁל־בָּנוּ קֶצֶף, כִּי לְךָ עֵינֵינוּ תְלוּיוֹת. הוֹשִׁיעֵנוּ לְמַעַן שְׁמֶךָ  רַחֵם עָלֵינוּ לְמַעַן בְּרִיתֶךָ. הַבִּיטָה וַעֲנֵנוּ בְּעֵת צָרָה כִּי לְךָ יְיָ הַיְשׁוּעָה. בְּךָ תוֹחַלְתֵּנוּ אֱלוֹהַּ סְלִיחוֹת, אָנָּא סְלַח נָא אֵל טוֹב וְסַלָּח, כִּי אֵל מֶלֶךְ חַנּוּן וְרַחוּם אָתָּה.
        ///
        ///אָנָּא מֶלֶךְ חַנּוּן וְרַחוּם, זְכֹר וְהַבֵּט לִבְרִית בֵּין הַבְּתָרִים וְתֵרָאֶה לְפָ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TachanunBH4 {
            get {
                return ResourceManager.GetString("TachanunBH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אֵין כָּמוֹךָ חַנּוּן וְרַחוּם יְיָ אֱלֹהֵינוּ, אֵין כָּמוֹךָ אֵל אֶרֶךְ אַפַּיִם וְרַב חֶסֶד וֶאֱמֶת, הוֹשִׁיעֵנוּ בְּרַחֲמֶיךָ הָרַבִּים, מֵרַעַשׁ וּמֵרֹגֶז הַצִּילֵנוּ. זְכֹר לַעֲבָדֶיךָ לְאַבְרָהָם לְיִצְחָק וּלְיַעֲקֹב, אַל תֵּפֶן אֶל קָשְׁיֵנוּ וְאֶל רִשְׁעֵנו וְאֶל חַטָּאתֵנוּ. שׁוּב מֵחֲרוֹן אַפֶּךָ וְהִנָּחֵם עַל הָרָעָה לְעַמֶּךָ. וְהָסֵר מִמֶּנּוּ מַכַּת הַמָּוֶת כִּי רַחוּם אָתָּה, כִּי כֵן דַּרְכֶּךָ, עוֹשֶׂה חֶסֶד חִנָּם בְּכָל דּוֹר וָדוֹר. חוּסָה יְיָ עַל עַמֶּךָ וְהַצִּילֵנוּ מִזַּעְמֶךָ, ו [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TachanunBH5 {
            get {
                return ResourceManager.GetString("TachanunBH5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הַפּוֹתֵחַ יָד בִּתְשׁוּבָה לְקַבֵּל פּוֹשְׁעִים וְחַטָּאִים, נִבְהֲלָה נַפְשֵׁנוּ מֵרֹב עִצְּבוֹנֵנוּ, וְאַל תִּשְׁכָּחֵנוּ נֶצַח. קוּמָה וְהוֹשִׁיעֵנוּ כִּי חָסִינוּ בָךְ. אָבִינוּ מַלְכֵּנוּ, אִם אֵין בָּנוּ צְדָקָה וּמַעֲשִׂים טוֹבִים, זְכָר לָנוּ אֶת בְּרִית אֲבוֹתֵינוּ וְעֵדוֹתֵינוּ בְּכָל יוֹם,  יְיָ אֶחָד. הַבִּיטָה בְעָנְיֵנוּ כִּי רַבּוּ מַכְאוֹבֵינוּ וְצָרוֹת לְבָבֵנוּ. חוּסָה יְיָ עָלֵינוּ בְּאֶרֶץ שִׁבְיֵנוּ וְאַל תִּשְׁפֹּךְ חֲרוֹנְךָ עָלֵינוּ כִּי אֲנַחְנוּ עַמְּךָ בְּנֵי בְרִיתֶךָ. אֵל, הַבִּיטָה דַּל כְּבוֹדֵנוּ בַּגּוֹיִם וְשִׁק [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TachanunBH6 {
            get {
                return ResourceManager.GetString("TachanunBH6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יְיָ אֱלֹהֵי יִשְׂרָאֵל, שׁוּב מֵחֲרוֹן אַפֶּךָ וְהִנָּחֵם עַל הָרָעָה לְעַמֶּךָ.
        ///
        ///הַבֵּט מִשָּׁמַיִם וּרְאֵה כִּי הָיִינוּ לַעַג וָקֶלֶס בַּגּוֹיִם, 
        ///נֶחְשַׁבְנוּ כְּצֹּאן לַטֶּבַח יוּבָל, לַהֲרֹג וּלְאַבֵּד וּלְמַכָּה וּלְחֶרְפָּה.
        ///
        ///וּבְכָל זֹאת שִׁמְךָ לֹא שָׁכָחְנוּ, נָא אַל תִּשְׁכָּחֵנוּ.
        ///
        ///יְיָ אֱלֹהֵי יִשְׂרָאֵל, שׁוּב מֵחֲרוֹן אַפֶּךָ וְהִנָּחֵם עַל הָרָעָה לְעַמֶּךָ.
        ///
        ///זָרִים אוֹמְרִים אֵין תּוֹחֶלֶת וְתִקְוָה, 
        ///חֹן אֹם לְשִׁמְךָ מְקַוֶּה, טָהוֹר, יְשׁוּעָתֵנוּ קָרְבָה, 
        ///יָגַעְנוּ וְלֹא ה [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TachanunBH7 {
            get {
                return ResourceManager.GetString("TachanunBH7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חוּסָה יְיָ עָלֵינוּ בְּרַחֲמֶיךָ וְאַל תִּתְּנֵנוּ בִּידֵי אַכְזָרִים.
        ///לָמָּה יֹאמְרוּ הַגּוֹיִם אַיֵּה נָא אֱלֹהֵיהֶם, 
        ///לְמַעַנְךָ עֲשֵׂה עִמָּנוּ חֶסֶד וְאַל תְּאַחַר.
        ///
        ///אָנָּא שׁוּב מֵחֲרוֹנְךָ וְרַחֵם סְגֻלָּה אֲשֶׁר בָּחָרְתָּ.
        ///
        ///יְיָ אֱלֹהֵי יִשְׂרָאֵל, שׁוּב מֵחֲרוֹן אַפֶּךָ וְהִנָּחֵם עַל הָרָעָה לְעַמֶּךָ.
        ///
        ///קוֹלֵנוּ תִשְׁמַע וְתָחֹן, וְאַל תִּטְּשנוּ בְּיַד אֹיְבֵינוּ לִמְחוֹת אֶת שְׁמֵנוּ. 
        ///זְכֹר אֲשֶׁר נִשְׁבַּעְתָּ לַאֲבוֹתֵינוּ כְּכוֹכְבֵי הַשָּׁמַיִם אַרְבֶּה אֶת זַרְעֲכֶם, 
        ///וְעַתָּה  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TachanunBH8 {
            get {
                return ResourceManager.GetString("TachanunBH8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שׁוֹמֵר יִשְׂרָאֵל, שְׁמֹר שְׁאֵרִית יִשְׂרָאֵל, וְאַל יֹאבַד יִשְׂרָאֵל, הָאוֹמְרִים: שְׁמַע יִשְׂרָאֵל.
        ///שׁוֹמֵר גּוֹי אֶחָד, שְׁמֹר שְׁאֵרִית עַם אֶחָד, וְאַל יֹאבַד גּוֹי אֶחָד, הַמְּיַחֲדִים שִׁמְךָ, יְיָ אֱלֹהֵינוּ יְיָ אֶחָד.
        ///שׁוֹמֵר גּוֹי קָדוֹשׁ, שְׁמֹר שְׁאֵרִית עַם קְדוֹשׁ, וְאַל יֹאבַד גּוֹי קָדוֹשׁ, הַמְשַׁלְּשִׁים בְּשָׁלֹשׁ קְדֻשּׁוֹת לְקָדוֹשׁ.
        ///מִתְרַצֶּה בְּרַחֲמִים וּמִתְפַּיֵּס בְּתַחֲנוּנִים, הִתְרַצֶּה וְהִתְפַּיֵּס לְדוֹר עָנִי, כִּי אֵין עוֹזֵר. אָבִינוּ מַלְכֵּנוּ, חָנֵּנוּ וַעֲנֵנ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TachanunEnding {
            get {
                return ResourceManager.GetString("TachanunEnding", resourceCulture);
            }
        }
    }
}
