//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrayPal.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrayPal.Common.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערבית.
        /// </summary>
        public static string Arvit {
            get {
                return ResourceManager.GetString("Arvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערבית.
        /// </summary>
        public static string ArvitTitle {
            get {
                return ResourceManager.GetString("ArvitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ט&quot;ו באב.
        /// </summary>
        public static string Av15thTitle {
            get {
                return ResourceManager.GetString("Av15thTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תשעה באב.
        /// </summary>
        public static string Av9thTitle {
            get {
                return ResourceManager.GetString("Av9thTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברך עלינו.
        /// </summary>
        public static string BarechAleinuTitle {
            get {
                return ResourceManager.GetString("BarechAleinuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר ראשון של חנוכה.
        /// </summary>
        public static string Chanuka1 {
            get {
                return ResourceManager.GetString("Chanuka1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר שני של חנוכה.
        /// </summary>
        public static string Chanuka2 {
            get {
                return ResourceManager.GetString("Chanuka2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר שלישי של חנוכה.
        /// </summary>
        public static string Chanuka3 {
            get {
                return ResourceManager.GetString("Chanuka3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר רביעי של חנוכה.
        /// </summary>
        public static string Chanuka4 {
            get {
                return ResourceManager.GetString("Chanuka4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר חמישי של חנוכה.
        /// </summary>
        public static string Chanuka5 {
            get {
                return ResourceManager.GetString("Chanuka5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר שישי של חנוכה.
        /// </summary>
        public static string Chanuka6 {
            get {
                return ResourceManager.GetString("Chanuka6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר שביעי של חנוכה.
        /// </summary>
        public static string Chanuka7 {
            get {
                return ResourceManager.GetString("Chanuka7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נר שמיני של חנוכה.
        /// </summary>
        public static string Chanuka8 {
            get {
                return ResourceManager.GetString("Chanuka8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דף יומי.
        /// </summary>
        public static string DafYomiTitle {
            get {
                return ResourceManager.GetString("DafYomiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוף זמן קריאת שמע.
        /// </summary>
        public static string EndTimeOfShma {
            get {
                return ResourceManager.GetString("EndTimeOfShma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צום גדליה.
        /// </summary>
        public static string GdaliahFastTitle {
            get {
                return ResourceManager.GetString("GdaliahFastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תשרי|חשוון|כסלו|טבת|שבט|אדר|אדר א&apos;|אדר ב&apos;|ניסן|אייר|סיוון|תמוז|אב|אלול.
        /// </summary>
        public static string HebMonths {
            get {
                return ResourceManager.GetString("HebMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הושענא רבה.
        /// </summary>
        public static string HoshaanaRabaTitle {
            get {
                return ResourceManager.GetString("HoshaanaRabaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שבת.
        /// </summary>
        public static string KnissatShabbat {
            get {
                return ResourceManager.GetString("KnissatShabbat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זמן קריאת שמע יסתיים ב-{0}..
        /// </summary>
        public static string KriatShmaReminderText {
            get {
                return ResourceManager.GetString("KriatShmaReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ל&quot;ג בעומר.
        /// </summary>
        public static string LagBaomerTitle {
            get {
                return ResourceManager.GetString("LagBaomerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מעריב.
        /// </summary>
        public static string MaarivTitle {
            get {
                return ResourceManager.GetString("MaarivTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנחה.
        /// </summary>
        public static string Mincha {
            get {
                return ResourceManager.GetString("Mincha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זמן תפילת מנחה יסתיים ב-{0}..
        /// </summary>
        public static string MinchaReminderText {
            get {
                return ResourceManager.GetString("MinchaReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנחה.
        /// </summary>
        public static string MinchaTitle {
            get {
                return ResourceManager.GetString("MinchaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אשכנז.
        /// </summary>
        public static string NusachAshkenazTitle {
            get {
                return ResourceManager.GetString("NusachAshkenazTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בלדי.
        /// </summary>
        public static string NusachBaladiTitle {
            get {
                return ResourceManager.GetString("NusachBaladiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדות המזרח.
        /// </summary>
        public static string NusachEdotMizrachTitle {
            get {
                return ResourceManager.GetString("NusachEdotMizrachTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ספרד.
        /// </summary>
        public static string NusachSfardTitle {
            get {
                return ResourceManager.GetString("NusachSfardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יום 1 לעומר.
        /// </summary>
        public static string Omer1 {
            get {
                return ResourceManager.GetString("Omer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‏{0} ימים לעומר.
        /// </summary>
        public static string OmerShort {
            get {
                return ResourceManager.GetString("OmerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אור ל{0}.
        /// </summary>
        public static string OrLe {
            get {
                return ResourceManager.GetString("OrLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרשת {0}.
        /// </summary>
        public static string ParashaNameTitleFormat {
            get {
                return ResourceManager.GetString("ParashaNameTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פסח שני.
        /// </summary>
        public static string Pesach2Title {
            get {
                return ResourceManager.GetString("Pesach2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אסרו חג פסח.
        /// </summary>
        public static string PesachDTitle {
            get {
                return ResourceManager.GetString("PesachDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חול המועד פסח.
        /// </summary>
        public static string PesachHmTitle {
            get {
                return ResourceManager.GetString("PesachHmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פסח.
        /// </summary>
        public static string PesachTitle {
            get {
                return ResourceManager.GetString("PesachTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פורים קטן.
        /// </summary>
        public static string PurimKatanTitle {
            get {
                return ResourceManager.GetString("PurimKatanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פורים.
        /// </summary>
        public static string PurimTitle {
            get {
                return ResourceManager.GetString("PurimTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ראש חודש {0}.
        /// </summary>
        public static string RoshChodeshTitle_F0 {
            get {
                return ResourceManager.GetString("RoshChodeshTitle_F0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ראש השנה.
        /// </summary>
        public static string RoshHashanaTitle {
            get {
                return ResourceManager.GetString("RoshHashanaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שחרית.
        /// </summary>
        public static string Shacharit {
            get {
                return ResourceManager.GetString("Shacharit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זמן תפילת שחרית יסתיים ב-{0}..
        /// </summary>
        public static string ShacharitReminderText {
            get {
                return ResourceManager.GetString("ShacharitReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שחרית.
        /// </summary>
        public static string ShacharitTitle {
            get {
                return ResourceManager.GetString("ShacharitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אסרו חג שבועות.
        /// </summary>
        public static string ShavuotDTitle {
            get {
                return ResourceManager.GetString("ShavuotDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שבועות.
        /// </summary>
        public static string ShavuotTitle {
            get {
                return ResourceManager.GetString("ShavuotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמיני עצרת.
        /// </summary>
        public static string ShminiAtzeretTitle {
            get {
                return ResourceManager.GetString("ShminiAtzeretTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שושן פורים.
        /// </summary>
        public static string ShushanPurimTitle {
            get {
                return ResourceManager.GetString("ShushanPurimTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ט&quot;ו בשבט.
        /// </summary>
        public static string Shvat15thTitle {
            get {
                return ResourceManager.GetString("Shvat15thTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מתחילים לומר &quot;{0}&quot;..
        /// </summary>
        public static string StartSaying {
            get {
                return ResourceManager.GetString("StartSaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אסרו חג סוכות.
        /// </summary>
        public static string SukkotDTitle {
            get {
                return ResourceManager.GetString("SukkotDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חול המועד סוכות.
        /// </summary>
        public static string SukkotHmTitle {
            get {
                return ResourceManager.GetString("SukkotHmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוכות.
        /// </summary>
        public static string SukkotTitle {
            get {
                return ResourceManager.GetString("SukkotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צום י&quot;ז בתמוז.
        /// </summary>
        public static string Tamuz17thTitle {
            get {
                return ResourceManager.GetString("Tamuz17thTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תענית בכורות.
        /// </summary>
        public static string TeanitBechorotTitle {
            get {
                return ResourceManager.GetString("TeanitBechorotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תענית אסתר.
        /// </summary>
        public static string TeanitEstherTitle {
            get {
                return ResourceManager.GetString("TeanitEstherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צום עשרה בטבת.
        /// </summary>
        public static string Tevet10thTitle {
            get {
                return ResourceManager.GetString("Tevet10thTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string TextWithComment_F1 {
            get {
                return ResourceManager.GetString("TextWithComment_F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ידוע.
        /// </summary>
        public static string UnknownNusach {
            get {
                return ResourceManager.GetString("UnknownNusach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ותן טל ומטר.
        /// </summary>
        public static string VetenTalUmatarTitle {
            get {
                return ResourceManager.GetString("VetenTalUmatarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יום העצמאות.
        /// </summary>
        public static string YomHaazmautTitle {
            get {
                return ResourceManager.GetString("YomHaazmautTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יום השואה.
        /// </summary>
        public static string YomHashoahTitle {
            get {
                return ResourceManager.GetString("YomHashoahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יום הזיכרון.
        /// </summary>
        public static string YomHazikaronTitle {
            get {
                return ResourceManager.GetString("YomHazikaronTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יום כיפור.
        /// </summary>
        public static string YomKippurTitle {
            get {
                return ResourceManager.GetString("YomKippurTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יום ירושלים.
        /// </summary>
        public static string YomYerushalaiymTitle {
            get {
                return ResourceManager.GetString("YomYerushalaiymTitle", resourceCulture);
            }
        }
    }
}
